### ISSUE TITLE
支付宝当面付，付款后不跳转

### ISSUE THREAD

**Issue by cc58c58** [assimon/dujiaoka#102]
支付宝当面付，都设置好了，也可以正常付款，但是付款后不会跳转，是不是支付宝没有设置授权回调地址，应该怎么弄？

**Comment by pwwq** [comment]
vhh

**Comment by ojbk8** [comment]
1. dujiaoka支付宝不需要设置授权回调地址,当然你也可以随便设，哪怕域名不对也是可以的。这点与ZFAKA不同。
2. 后台管理/admin设置可以使用反代端口(websocket,,vless回落端口…),但用户购买务必使用nginx监听listen的端口，否则付款后不跳转

**Comment by cc58c58** [comment]
> 1. dujiaoka支付宝不需要设置授权回调地址,当然你也可以随便设，哪怕域名不对也是可以的。这点与ZFAKA不同。
> 2. 后台管理/admin设置可以使用反代端口(websocket,,vless回落端口…),但用户购买务必使用nginx监听listen的端口，否则付款后不跳转

请问第2点具体该如何操作？有没有教程呢？

**Comment by assimon** [comment]
大概率是支付宝公钥错了

**Comment by cc58c58** [comment]
> 大概率是支付宝公钥错了

应该不会吧，付款后钱是可以收到了的；而且使用zfaka也是正常的

**Comment by assimon** [comment]
钱是可以收到因为付款用的是你的私钥，付款后回调使用支付宝公钥验证数据正确性。所以支付宝公钥填写错了不会影响支付，只是会影响回调消息验证

**Comment by ahjxm** [comment]
一样 当面付 付款后 不跳转  重新配置了公私 密匙都不可以

**Comment by assimon** [comment]
https://www.bilibili.com/s/video/BV11e411x7ab

**Comment by hulisang** [comment]
解决了吗，我这里也不会回调，测试发现是开了CF的cdn导致，防火墙放行回调路径/pay/alipay还是不行

**Comment by cc58c58** [comment]
> 解决了吗，我这里也不会回调，测试发现是开了CF的cdn导致，防火墙放行回调路径/pay/alipay还是不行

确实是CF的CND有问题，关闭CDN就可以回调了

**Comment by morying** [comment]
> > 解决了吗，我这里也不会回调，测试发现是开了CF的cdn导致，防火墙放行回调路径/pay/alipay还是不行
> 
> 确实是CF的CND有问题，关闭CDN就可以回调了
你好，你是怎么解决的呢。谢谢赐教。

**Comment by jakkpop** [comment]
题主解决了吗？我也是遇到这个问题。。
公钥和密钥都是正确的，可以付款而且已经到账了，但付款后就是不跳转。。

**Comment by YangMin** [comment]
支付宝当面付，钱收到了
有时候可以跳转，有时候不行，什么原因呢？如何解决？

**Comment by heiniao998** [comment]
大概率是宝塔let证书问题 裸奔试试

**Comment by kimsmel** [comment]
除了CDN，就是证书问题，去掉证书再试试
