### ISSUE TITLE
卡密库存计算问题

### ISSUE THREAD

**Issue by YulinChan** [assimon/dujiaoka#106]
我添加有一个卡密（数量为1），我点进去下单，但没有付款，退出来回到首页，发现库存为零了，等了好久也没恢复。
![pic](https://p.ananas.chaoxing.com/star3/origin/09c1e3e0eb6a5c6209873251e19d35af.png)

补充：
过了一个小时，库存恢复了。

建议付款后再减库存，或者付款时间过了还没付款的恢复库存。

**Comment by assimon** [comment]
.env里面可以配置库存恢复时间
# 订单过期时间 单位为分钟
ORDER_EXPIRE_DATE=3

**Comment by YulinChan** [comment]
我没改过ORDER_EXPIRE_DATE这参数，它默认3分钟。但3分钟过后没有恢复，大概是1小时才恢复的。

**Comment by assimon** [comment]
可能是服务器卡了把，进程没缓过来，之前也没遇到有人提过这个错误。
