### ISSUE TITLE
希望增加stripe支持

### ISSUE THREAD

**Issue by Alan-yhq** [assimon/dujiaoka#107]
如题

**Comment by assimon** [comment]
stripe没有测试账号/(ㄒoㄒ)/~~

**Comment by iLay1678** [comment]
> stripe没有测试账号/(ㄒoㄒ)/~~

其实魔改已经有stripe了，支持stripe的微信和支付宝

**Comment by iLay1678** [comment]
> stripe没有测试账号/(ㄒoㄒ)/~~

魔改版已经实现，包括微信支付宝和信用卡支付

**Comment by betaxab** [comment]
@iLay1678 大佬能不能合并过来啊？谢谢~

**Comment by galaxychuck** [comment]
> > stripe没有测试账号/(ㄒoㄒ)/~~
> 
> 其实魔改已经有stripe了，支持stripe的微信和支付宝

请求合并…
