### ISSUE TITLE
极验证已经关闭，但是下单是时候却提示请正确完成行为认证

### ISSUE THREAD

**Issue by Amiking** [assimon/dujiaoka#109]
![image](https://user-images.githubusercontent.com/63540385/97097617-55d35a80-16ad-11eb-9e46-05987b4ead2b.png)
极验证已经关闭，但是下单是时候却提示请正确完成行为认证

**Comment by assimon** [comment]
感谢反馈，等待更新

**Comment by assimon** [comment]
问题已解决，请覆盖1.8.1的代码即可，无需其他操作

**Comment by Amiking** [comment]
好的好的，感谢大佬，点赞
