### ISSUE TITLE
luna 模板

### ISSUE THREAD

**Issue by 1515806183** [assimon/dujiaoka#110]
设置前台模板为luna
报错如下
ErrorException (E_ERROR)
htmlspecialchars() expects parameter 1 to be string, object given (View: /www/admin/faka_80/wwwroot/dujiaoka/resources/views/luna/layouts/_nav.blade.php) (View: /www/admin/faka_80/wwwroot/dujiaoka/resources/views/luna/layouts/_nav.blade.php)
Previous exceptions
htmlspecialchars() expects parameter 1 to be string, object given (View: /www/admin/faka_80/wwwroot/dujiaoka/resources/views/luna/layouts/_nav.blade.php) (0)
htmlspecialchars() expects parameter 1 to be string, object given (0)

**Comment by 1515806183** [comment]
php artisan dujiao install
重新导入下数据即可

**Comment by assimon** [comment]
解决了吗

**Comment by 1515806183** [comment]
嗯
