### ISSUE TITLE
建议加入recaptcha

### ISSUE THREAD

**Issue by YulinChan** [assimon/dujiaoka#112]
极验似乎不太好申请啊，价格啥的也没说，希望大佬能加入recaptcha，这个有足够多的免费额度，个人使用完全没问题。

**Comment by assimon** [comment]
我觉得你说的有道理

**Comment by 9ikj** [comment]
www.vaptcha.com
也挺好申请的

**Comment by xb0or** [comment]
recaptcha国内有的打不开吧hcaptcha也可以的

**Comment by dylanbai8** [comment]
腾讯防水墙 也不错

**Comment by sakura-yuina** [comment]
> recaptcha国内有的打不开吧hcaptcha也可以的

recaptcha.net/recaptcha/api.js 是reCAPTCHA的国内镜像地址,有北京和上海节点

hcaptcha过于反人类,而且机器人绕过(bypass)及其简单,不推荐使用
