### ISSUE TITLE
友情提醒，不算BUG，1.8.1后台忘改版本号了

### ISSUE THREAD

**Issue by CNBOY239** [assimon/dujiaoka#114]
存在的问题：
更新1.8.1，后台还是显示1.8.0

说明：
一直关注和使用，LOC论坛坛友。昨晚的修正版本1.8.1发布，早上第一时间更新。但是大佬你好像忘记改版本号了，更新完还是1.8.0。

修正：
查阅 /resources/views/admin/dashboard/title.blade.php，显示的：当前系统版本：V1.8.0。自己手动改成1.8.1，就显示正常了。

**Comment by assimon** [comment]
这个无伤大雅，嘻嘻
