### ISSUE TITLE
邮件问题

### ISSUE THREAD

**Issue by wangwangyh** [assimon/dujiaoka#116]
想请问一下大佬，为啥邮件有些人有发，有些人没法阿。什么原因，用的是126的邮箱。配置如下，
# 邮件服务配置
MAIL_DRIVER=smtp
MAIL_HOST=smtp.126.com
MAIL_PORT=465
MAIL_USERNAME=account
MAIL_PASSWORD=secret
MAIL_FROM_ADDRESS=account@126.com
MAIL_FROM_NAME=bobo小店
MAIL_ENCRYPTION=ssl

**Comment by wangwangyh** [comment]
已经升级到最新版本

**Comment by assimon** [comment]
你的意思是有的收的到邮件，有的收不到？

**Comment by CNBOY239** [comment]
借贴跟问一下老兄。看教程，邮箱协议只说是TLS/SSL两种。我用的O365的邮箱，官方给出是STARTTLS。
是不是不管任何邮箱服务商，也不管官方给出协议是什么，咱这个只能是TLS/SSL两种中尝试，哪种成功用哪种？

**Comment by assimon** [comment]
STARTTLS不就是tls？

**Comment by CNBOY239** [comment]
> STARTTLS不就是tls？

明白了，谢谢！

**Comment by wangwangyh** [comment]
> 你的意思是有的收的到邮件，有的收不到？

对的。大佬 。我看了一下邮箱的已发送记录。。有几封，我自己测试了一下又没有收到

**Comment by assimon** [comment]
正常，你用的又不是付费邮件推送服务，网上免费邮箱哪能给你随便发
