### ISSUE TITLE
当面支付问题

### ISSUE THREAD

**Issue by StarDream521** [assimon/dujiaoka#119]
我看了你哔哩哔哩的视频 照着做了
但我支付的时候 页面postOrder
显示500 服务器错误
请问是什么情况？[
![问题](https://user-images.githubusercontent.com/40490183/98121509-491de600-1ea7-11eb-903b-fef3f94a27dc.png)
](url)

**Comment by assimon** [comment]
开debug看原因

**Comment by StarDream521** [comment]
抱歉 请问如何开启

**Comment by assimon** [comment]
> 抱歉 请问如何开启

.env 文件里面的APP_DEBUG=true
会关还不会开么==

**Comment by StarDream521** [comment]
![1](https://user-images.githubusercontent.com/40490183/98123952-79b34f00-1eaa-11eb-9599-e6e3b16fecc8.png)

**Comment by assimon** [comment]
redis没配置或没启动，看安装的视频教程吧。redis连不上

**Comment by StarDream521** [comment]
很抱歉
![2](https://user-images.githubusercontent.com/40490183/98125280-30fc9580-1eac-11eb-8271-0d896fe0c35a.png)
我看了教程 没说怎么启动和配置    php7.2版本 我也安装了。。。

**Comment by StarDream521** [comment]
对不起 可以帮忙解答一下吗

**Comment by StarDream521** [comment]
我用的是windows系统
