### ISSUE TITLE
请问paypal付款问题

### ISSUE THREAD

**Issue by chunlee8189** [assimon/dujiaoka#123]
在paypal沙箱测试付款都没出现问题，会回到付款成功画面并且发卡
但我改成live模式，自己尝试付款成功后，网站无法回到成功画面会卡住
[![DePTDx.png](https://s3.ax1x.com/2020/11/17/DePTDx.png)](https://imgchr.com/i/DePTDx)

请问如何解决？

**Comment by chunlee8189** [comment]
忘记还有在后台会显示在代处理订单，不会到已完成

**Comment by assimon** [comment]
> 忘记还有在后台会显示在代处理订单，不会到已完成

开debug看是不是报错了

**Comment by chunlee8189** [comment]
[2020-11-17 23:06:23] local.ERROR: 支付通道异常~ {"error":"invalid_client","error_description":"Client Authentication failed"} {"exception":"[object] (App\\Exceptions\\AppException(code: 0): 支付通道异常~ {\"error\":\"invalid_client\",\"error_description\":\"Client Authentication failed\"} at /www/wwwroot/****.***/dujiaoka_build/app/Http/Controllers/Pay/PaypalPayController.php:75)
[stacktrace]
#0 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Pay\\PaypalPayController->gateway('13', 'ABT202011173309...')
#1 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('gateway', Array)
#2 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Pay\\PaypalPayController), 'gateway')
#3 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#4 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()
#5 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#6 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#7 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#8 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#9 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#10 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#11 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#12 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#13 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#14 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#20 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#21 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#22 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#23 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#24 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#25 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /www/wwwroot/****.***/dujiaoka_build/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#37 /www/wwwroot/****.***/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#38 /www/wwwroot/****.***/dujiaoka_build/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#39 {main}
"} 

看不懂  😂️😂️

**Comment by assimon** [comment]
这个是回调效验失败了好像

> [2020-11-17 23:06:23] local.ERROR: 支付通道异常~ {"error":"invalid_client","error_description":"Client Authentication failed"} {"exception":"[object] (App\Exceptions\AppException(code: 0): 支付通道异常~ {"error":"invalid_client","error_description":"Client Authentication failed"} at /www/wwwroot/__**.**_/dujiaoka_build/app/Http/Controllers/Pay/PaypalPayController.php:75) [stacktrace] #0 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\Pay\PaypalPayController->gateway('13', 'ABT202011173309...')
> #1 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('gateway', Array) #2 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Pay\PaypalPayController), 'gateway')
> #3 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController() #4 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
> #5 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #6 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #7 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure)) #8 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #9 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure)) #10 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #11 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure)) #12 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #13 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure)) #14 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #15 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure)) #16 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #17 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure)) #18 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #19 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #20 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
> #21 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route)) #22 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
> #23 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #24 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
> #25 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #26 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
> #27 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #28 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
> #29 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #30 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
> #31 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #32 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
> #33 /www/wwwroot/__**.**_/dujiaoka_build/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #34 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
> #35 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #36 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
> #37 /www/wwwroot/__**.**_/dujiaoka_build/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request)) #38 /www/wwwroot/__**.**_/dujiaoka_build/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
> #39 {main}
> "}
> 
> 看不懂 😂️😂️

**Comment by assimon** [comment]
机器是国内的吗，会不会请求paypal超时了

**Comment by w8951858** [comment]
同样的问题！Paypal支付后可正常收到款，但是无订单也不自动发卡！
支付网关填写了商户ID和商户密匙，其余未填未修改。
服务器在香港，通信正常！开了CDN！
麻烦大佬查查什么问题！可配合测试！

> 

> 
![微信截图_20201121164705](https://user-images.githubusercontent.com/22910041/99872049-f28c0800-2c19-11eb-87a8-ae4282ef4563.png)

**Comment by chunlee8189** [comment]
> 机器是国内的吗，会不会请求paypal超时了

不是噢！ 我是美国VPS，没开防火墙，没开CDN

**Comment by chunlee8189** [comment]
我记得paypal api 有新旧版  v1 v2版本！ 是不是版本差异导致？

**Comment by assimon** [comment]
> 同样的问题！Paypal支付后可正常收到款，但是无订单也不自动发卡！
> 支付网关填写了商户ID和商户密匙，其余未填未修改。
> 服务器在香港，通信正常！开了CDN！
> 麻烦大佬查查什么问题！可配合测试！
> 
> > 
> 
> > 
> 
> ![微信截图_20201121164705](https://user-images.githubusercontent.com/22910041/99872049-f28c0800-2c19-11eb-87a8-ae4282ef4563.png)

去掉CDN试试，.env里面的paypal沙箱关闭看看

**Comment by assimon** [comment]
> 我记得paypal api 有新旧版 v1 v2版本！ 是不是版本差异导致？

有可能，说实话我这边也没有使用过paypal，对接都是走的沙箱，我也不太清楚你信吗o(╥﹏╥)o

**Comment by lpn418** [comment]
同样的问题，1.8.2版本 沙箱正常，但live就会出现问题，上个月还是正常使用的，这个月开始不行了
![image](https://user-images.githubusercontent.com/51897247/104835892-a9d49080-58e4-11eb-89ff-d6545da5bd87.png)

**Comment by lpn418** [comment]
> 我记得paypal api 有新旧版 v1 v2版本！ 是不是版本差异导致？

伙计，找到原因了吗，同样的问题，之前都是正常的，这个月开始貌似不正常了
