### ISSUE TITLE
支付宝当面付不会自动跳转。订单系统也没有差到相关的订单信息

### ISSUE THREAD

**Issue by Lockey-J** [assimon/dujiaoka#124]
支付宝当面付不会自动跳转。订单系统也没有差到相关的订单信息。这是哪里出了问题么。公钥跟私钥都已经按教程设置好了。

**Comment by assimon** [comment]
看看是不是cdn拦截了，或者一般是支付宝公钥错了

**Comment by Lockey-J** [comment]
> 看看是不是cdn拦截了，或者一般是支付宝公钥错了

不是，找到问题了。不能修改局域网的IP做为URL。我直接用上域名就正常跳转了。我刚开始在.env里把URL设置成192.168.*.*这样是不会自动跳转的。一直是在等待支付
