### ISSUE TITLE
商品太多，有几十个的那种

### ISSUE THREAD

**Issue by chichdeng** [assimon/dujiaoka#130]
能否新增一个选项卡那样的模板？

**Comment by chichdeng** [comment]
希望可以增加一下微信订单通知，例如方糖server之类的

**Comment by assimon** [comment]
有server酱通知哈

**Comment by chichdeng** [comment]
> 有server酱通知哈

目前个人来说，商品60种以上，很不好看，希望有选项卡类似的模板，或者🈶下拉框分类选择显示那样的。
