### ISSUE TITLE
🤘商品密码功能谢谢~

### ISSUE THREAD

**Issue by yxblog** [assimon/dujiaoka#133]
试用了下，挺好的，有代发，优惠券，多件打折，但是发现没有商品密码功能耶！比如某个商品开放给特定客户比如代理，不想给普通客户看到，大佬，有木有考虑下~😝

**Comment by assimon** [comment]
> 试用了下，挺好的，有代发，优惠券，多件打折，但是发现没有商品密码功能耶！比如某个商品开放给特定客户比如代理，不想给普通客户看到，大佬，有木有考虑下~😝

计划中
