### ISSUE TITLE
安装后 版本显示1.8.0

### ISSUE THREAD

**Issue by t-o-n-y-w** [assimon/dujiaoka#136]
下载的1.8.1版本的安装包。
安装成功后 显示的却是1.8.0版本？
这是啥情况呀？大佬？

**Comment by assimon** [comment]
> 下载的1.8.1版本的安装包。
> 安装成功后 显示的却是1.8.0版本？
> 这是啥情况呀？大佬？

我忘了改版号，无伤大雅，小问题不影响功能

**Comment by t-o-n-y-w** [comment]
嗯嗯 谢谢啦 问一下 QQ的免签 如何实现呀

**Comment by assimon** [comment]
> 嗯嗯 谢谢啦 问一下 QQ的免签 如何实现呀

免签支付实现方式不在程序讨论范围内，QQ可以选择易支付
