### ISSUE TITLE
配置微信扫码付款，显示:mch_id参数格式错误

### ISSUE THREAD

**Issue by nuyoahaoyun** [assimon/dujiaoka#137]
支付通道异常~ERROR_GATEWAY: Get Wechat API Error:mch_id参数格式错误

按提示正确的填写的商户号，和商户密匙，应该没问题成功发起支付了，但是显示muh_ID

**Comment by assimon** [comment]
> 支付通道异常~ERROR_GATEWAY: Get Wechat API Error:mch_id参数格式错误
> 
> 按提示正确的填写的商户号，和商户密匙，应该没问题成功发起支付了，但是显示muh_ID

https://www.ifking.cn/p/316.html

供参考

**Comment by nuyoahaoyun** [comment]
> > 支付通道异常~ERROR_GATEWAY: Get Wechat API Error:mch_id参数格式错误
> > 按提示正确的填写的商户号，和商户密匙，应该没问题成功发起支付了，但是显示muh_ID
> 
> https://www.ifking.cn/p/316.html
> 
> 供参考

已解决，部署的时候没看到这个帖子
