### ISSUE TITLE
麻瓜宝 跳转 500错误

### ISSUE THREAD

**Issue by CyberSing** [assimon/dujiaoka#138]
[![r8jAW4.png](https://s3.ax1x.com/2020/12/17/r8jAW4.png)](https://imgchr.com/i/r8jAW4)

如图，https://xx.***.com/postOrder 所示

.env的https也等于true

支付网关也按照 https://www.ifking.cn/p/316.html 来设置

关了 宝塔 防跨站，依旧是这样

PS：套了CF

**Comment by assimon** [comment]
开debug看看具体报错

**Comment by CyberSing** [comment]
被蠢哭……原来是Redis它自己关闭了……重启就好了……
（话说它为什么会自己关闭……）
