### ISSUE TITLE
下载1.8.1安装后显示1.7.14，界面和演示界面不一样，演示那个好看的多啊

### ISSUE THREAD

**Issue by dayn97** [assimon/dujiaoka#139]
下载1.8.1安装后显示1.7.14，界面和演示界面不一样，演示那个好看的多啊，谢谢能帮助回答解决。

**Comment by assimon** [comment]
1.7.14是框架的版本，不是独家的版本
演示界面是luna模板，https://github.com/assimon/dujiaoka/blob/master/wikis/problems.md#%E6%9B%B4%E6%8D%A2%E6%A8%A1%E6%9D%BF
参考更换模板方法

> 下载1.8.1安装后显示1.7.14，界面和演示界面不一样，演示那个好看的多啊，谢谢能帮助回答解决。

**Comment by dayn97** [comment]
感谢
