### ISSUE TITLE
后台卡密显示异常

### ISSUE THREAD

**Issue by hotket** [assimon/dujiaoka#14]
1、管理员添加了5个卡密，显示为未售出。
2‘新开浏览器去前台购买一个卡密，支付宝当面付支付成功后成功提取到卡密。
3、回到后台管理员，再次点击卡密菜单，发现所有的卡密都显示为已售出状态。

**Comment by assimon** [comment]
> 1，管理员添加了5个卡密，显示为未售出
> 。2'新开浏览器去前台购买一个卡密，支付宝当面付支付成功后成功提取到卡密
> 。3，返回后台管理员，再次点击卡密菜单，发现所有的卡密都显示为已售出状态。

已修复这个问题，可以拉取更新后再次尝试
