### ISSUE TITLE
独角数卡 如何 与 vpay进行对接呀

### ISSUE THREAD

**Issue by t-o-n-y-w** [assimon/dujiaoka#145]

**Comment by assimon** [comment]
https://www.ifking.cn/p/316.html

**Comment by t-o-n-y-w** [comment]
通过 订单查询 的时候 不需要查询密码 这样会不会 存在安全风险呀

**Comment by t-o-n-y-w** [comment]
发布商品 为商品添加的图片 不显示 但在后台源码文件里面 可以看到 图片已经上传到服务器

**Comment by assimon** [comment]
认真看视频教程，.env把域名改成自己的
