### ISSUE TITLE
输入一个不存在的优惠码时会500

### ISSUE THREAD

**Issue by AlifeLine** [assimon/dujiaoka#147]
输入一个不存在的优惠码时会500
日志：
![捕获](https://user-images.githubusercontent.com/33149119/103274349-6d57f800-49fc-11eb-8a7a-9c7eaaa3972b.PNG)

不知道为什么这个文件的用户组变为了root，之前手动改过一次了，但是几天后又会出现这个问题
![logfile](https://user-images.githubusercontent.com/33149119/103274295-47325800-49fc-11eb-8351-a2e6750e2665.PNG)

**Comment by assimon** [comment]
这个日志权限问题，跟优惠无关，不知道你这边部署的时候做了哪些操作

**Comment by AlifeLine** [comment]
找到问题了，Supervisor的启动用户被我设置成了root
