### ISSUE TITLE
关于模板

### ISSUE THREAD

**Issue by baiguke2019** [assimon/dujiaoka#150]
大佬请问下 以下图片中是哪个模板？1.8.1中没有这个模板码？
![yyycode_com20200622122716](https://user-images.githubusercontent.com/44437213/103479278-9c5cd800-4e07-11eb-946b-d7ba68e4a8da.png)

**Comment by assimon** [comment]
这个是最早期版本的模板了，早就已经放弃了

**Comment by baiguke2019** [comment]
可惜了！ 1.8.1还能使用这个模板码？
感谢大佬的回复！

**Comment by baiguke2019** [comment]
> 这个是最早期版本的模板了，早就已经放弃了

可惜了！ 1.8.1还能使用这个模板码？
感谢大佬的回复！

**Comment by assimon** [comment]
不能了，这套模板兼容性不是很好

**Comment by baiguke2019** [comment]
好吧
