### ISSUE TITLE
更新1.8.2版本后server酱每次发送两条通知

### ISSUE THREAD

**Issue by ddgth** [assimon/dujiaoka#152]
更新1.8.2版本后server酱每次发送两条通知

**Comment by assimon** [comment]
重启一下supervisor进程

**Comment by wangwangyh** [comment]
> 重启一下supervisor进程
大佬你好，我更新了网站没了。我之前备份了。请问网站的数据之类的哪些是原来的商品信息之类的。。可以导入回去吗

**Comment by ddgth** [comment]
> > 重启一下supervisor进程
> > 大佬你好，我更新了网站没了。我之前备份了。请问网站的数据之类的哪些是原来的商品信息之类的。。可以导入回去吗

替作者回答下 如果之前数据库存在 那就可以还原

**Comment by wangwangyh** [comment]
> > > 重启一下supervisor进程
> > > 大佬你好，我更新了网站没了。我之前备份了。请问网站的数据之类的哪些是原来的商品信息之类的。。可以导入回去吗
> 
> 替作者回答下 如果之前数据库存在 那就可以还原

回复了怎么是500.。打不开。后台可以

**Comment by ddgth** [comment]
> > > > 重启一下supervisor进程
> > > > 大佬你好，我更新了网站没了。我之前备份了。请问网站的数据之类的哪些是原来的商品信息之类的。。可以导入回去吗
> > 
> > 
> > 替作者回答下 如果之前数据库存在 那就可以还原
> 
> 回复了怎么是500.。打不开。后台可以

重新走一遍升级流程 升级数据库试试

**Comment by wangwangyh** [comment]
> > > > > 重启一下supervisor进程
> > > > > 大佬你好，我更新了网站没了。我之前备份了。请问网站的数据之类的哪些是原来的商品信息之类的。。可以导入回去吗
> > > 
> > > 
> > > 替作者回答下 如果之前数据库存在 那就可以还原
> > 
> > 
> > 回复了怎么是500.。打不开。后台可以
> 
> 重新走一遍升级流程 升级数据库试试

谢谢老哥，重新终端升级了。。可以了
