### ISSUE TITLE
升级之后

### ISSUE THREAD

**Issue by wangwangyh** [assimon/dujiaoka#154]
升级之后，支付设置，商品全没了。。还可以找回吗？我备份了网站了。。不知道应该导入哪些文件

**Comment by kalidanmu** [comment]
数据库文件执行下就行了

**Comment by assimon** [comment]
我不清楚为什么升级会导致数据库没有了？升级命令不会清空数据库，除非你执行了其他操作

**Comment by wangwangyh** [comment]
> 我不清楚为什么升级会导致数据库没有了？升级命令不会清空数据库，除非你执行了其他操作

谢谢老大，导入数据库又好了。不知道为啥。。刚开始有问题。
