### ISSUE TITLE
关于微信打开发卡网提示用浏览器打开

### ISSUE THREAD

**Issue by conan-ux** [assimon/dujiaoka#155]
你好
      我看到resources/views/common/wechatqqjump.blade.php，这里您写了应该是微信打开链接的时候，提示用浏览器打开，我想在luna模板用这个，请问该怎么操作呢？

**Comment by assimon** [comment]
你用什么模板都会提示在浏览器打开，这是路由中间件。只要检测到你在微信和QQ都会提示你在浏览器打开

**Comment by conan-ux** [comment]
谢谢 可以了
