### ISSUE TITLE
后台菜单打不开，点击不跳转

### ISSUE THREAD

**Issue by cnpkmkk** [assimon/dujiaoka#156]
如题，后台菜单打不开，点击不跳转，还是处在原页面
多数菜单选项都无法打开
[![snpzJf.png](https://s3.ax1x.com/2021/01/08/snpzJf.png)](https://imgchr.com/i/snpzJf)

试过不用CDN访问，也是无法打开

开debug后复现，当页页面显示：
[![sn9uSU.png](https://s3.ax1x.com/2021/01/08/sn9uSU.png)](https://imgchr.com/i/sn9uSU)

**Comment by assimon** [comment]
更新的时候宝塔里面删干净再上传覆盖

**Comment by conan-ux** [comment]
我也出现这个问题了，我看更新教程里说直接上传覆盖就行了，没有说要删除，现在应该怎么解决呢？

**Comment by assimon** [comment]
把原宝塔老版本的代码删干净，然后上传1.8.2，解压，再执行升级命令

**Comment by conan-ux** [comment]
按你说的 已解决，建议更新教程里可以说一下需要删除旧版本，谢谢
