### ISSUE TITLE
Ubuntu18.04 LTS_php7.2报错Fatal error: require()

### ISSUE THREAD

**Issue by lxyok** [assimon/dujiaoka#16]
今天安装这个独角数卡网站。
安装环境
甲骨文日本机器 Ubuntu18.04 LTS_php7.2版本
到运行 `sudo -u www composer install` 这句命令
出现报错
`Your requirements could not be resolved to an installable set of packages.`
再次检查php版本，得到的版本号和宝塔一致。（不是常见问题里提到的情况）
我就运行这个命令（看起来像是另外一种安装composer的方法）
`curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/bin --filename=composer`
依然报错

报错内容
```
PHP Warning:  require(/www/wwwroot/lxyok.cf/vendor/autoload.php): failed to open stream: No such file or directory in /www/wwwroot/lxyok.cf/artisan on line 18

Warning: require(/www/wwwroot/lxyok.cf/vendor/autoload.php): failed to open stream: No such file or directory in /www/wwwroot/lxyok.cf/artisan on line 18
PHP Fatal error:  require(): Failed opening required '/www/wwwroot/lxyok.cf/vendor/autoload.php' (include_path='.:/www/server/php/72/lib/php') in /www/wwwroot/lxyok.cf/artisan on line 18

Fatal error: require(): Failed opening required '/www/wwwroot/lxyok.cf/vendor/autoload.php' (include_path='.:/www/server/php/72/lib/php') in /www/wwwroot/lxyok.cf/artisan on line 18

```

经过搜索发现 需要把
**`/etc/php/7.2/cli/php.ini`这个文件里的**
```
; UNIX: "/path1:/path2"
include_path = ".:/usr/share/php"
;
; Windows: "\path1;\path2"
;include_path = ".;c:\php\includes"

```
include_path 这个注释取消
我使用的VIM 编辑器
命令模式下 输入 `/include_path` 搜索到的第一个注释取消

然后运行 `sudo -u www composer install` 这句命令就不会报错了,后面的按照教程操作就成功了

这个是参考网站 https://github.com/composer/composer/issues/5510

**Comment by assimon** [comment]
> 今天安装这个独角数卡网站。
> 安装环境
> 甲骨文日本机器Ubuntu18.04 LTS_php7.2版本
> 到运行 这句`sudo -u www composer install`命令
> 出现报错再次
> `Your requirements could not be resolved to an installable set of packages.`
> 检查php版本，得到的版本号和宝塔一致。（不是常见问题里提到的情况）
> 我就运行这个命令（看起来像是另外一种安装composer的方法）
> `curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/bin --filename=composer`
> 依然报错
> 
> 报错内容
> 
> ```
> PHP Warning:  require(/www/wwwroot/lxyok.cf/vendor/autoload.php): failed to open stream: No such file or directory in /www/wwwroot/lxyok.cf/artisan on line 18
> 
> Warning: require(/www/wwwroot/lxyok.cf/vendor/autoload.php): failed to open stream: No such file or directory in /www/wwwroot/lxyok.cf/artisan on line 18
> PHP Fatal error:  require(): Failed opening required '/www/wwwroot/lxyok.cf/vendor/autoload.php' (include_path='.:/www/server/php/72/lib/php') in /www/wwwroot/lxyok.cf/artisan on line 18
> 
> Fatal error: require(): Failed opening required '/www/wwwroot/lxyok.cf/vendor/autoload.php' (include_path='.:/www/server/php/72/lib/php') in /www/wwwroot/lxyok.cf/artisan on line 18
> ```
> 
> 经过搜索发现需要把
> **`/etc/php/7.2/cli/php.ini`这个文件里的**
> 
> ```
> ; UNIX: "/path1:/path2"
> include_path = ".:/usr/share/php"
> ;
> ; Windows: "\path1;\path2"
> ;include_path = ".;c:\php\includes"
> ```
> 
> include_path这个注释取消
> 我使用的VIM编辑器
> 命令模式下输入`/include_path`搜索到的第一个注释取消
> 
> 然后运行`sudo -u www composer install`这句命令就不会报错了，后面的按照教程操作就成功了
> 
> 这个是参考网站[composer / composer＃5510](https://github.com/composer/composer/issues/5510)

感谢反馈
