### ISSUE TITLE
[Enhancement] 请求新增特性

### ISSUE THREAD

**Issue by betaxab** [assimon/dujiaoka#168]
希望可以添加如下功能：

1. 管理面板的 侧栏按钮和路由 写进 PHP 里，而不是调用 mysql；
2. 管理面板 多语言入口（我可以帮忙补全 English）；
3. 邮件模板应为 html template，可方便套用，而不是全塞进 mysql 里；
4. 代充输入框，也就是“自定义字段”可添加 radio、checkbox、textarea 类型；
5. 产品拖动排序功能。

还有，有没有兴趣将 AdminLTE 更换为像 Ant Design Pro 这样的现代化模板（当然可能有点复杂，但易用性和美观程度要好太多）？

谢谢。

**Comment by assimon** [comment]
1.这是laravel-admin的特性，我不会去改他的底层，毕竟后续还要更新
2.管理面板没必要多入口，其实这个程序功能特性还是国内使用者居多，很少有老外几乎没有
3.这个可以考虑，其实我最初塞进mysql的目的就是方便新手配置，不是每个人都会改html和做一些配置？很多人其实连.env配置都不会改，我已经在做傻瓜化操作了

**Comment by betaxab** [comment]
另外PR #167 语言帮忙合一下。修正了很多小问题。
