### ISSUE TITLE
支付回调只能异步回调吗

### ISSUE THREAD

**Issue by iLay1678** [assimon/dujiaoka#17]
我有个接口，异步回调只有国内服务器才能收到回调信息，国外无法收到，但是这个接口有单独的订单查询接口，能否加个通过主动查询判断支付状态

**Comment by assimon** [comment]
> 我有个接口，异步回调只有国内服务器才能收到回调信息，国外无法收到，但是这个接口有单独的订单查询接口，能否加个通过主动查询判断支付状态

这个可以根据异步回调代码自己修改同步回调控制器
