### ISSUE TITLE
请教下极验的问题

### ISSUE THREAD

**Issue by DevHjz** [assimon/dujiaoka#179]
大佬的独角数卡似乎在用极验，我也打算在我的个人网站上用极验，现在是免费版。
大佬用的是付费版吗？
如果有的话，我想请问下大佬用的极验付费版的报价是多少？我做个参考。谢谢！

**Comment by assimon** [comment]
我用的免费的......给不起钱o(╥﹏╥)o

**Comment by DevHjz** [comment]
> 我用的免费的......给不起钱o(╥﹏╥)o

好的，谢谢大佬！大佬在用免费版的时候有没有遇到速率限制？官方的客服不说。

**Comment by assimon** [comment]
暂时没有碰到，演示站量小

**Comment by DevHjz** [comment]
> 暂时没有碰到，演示站量小

好的，谢谢，麻烦了！
