### ISSUE TITLE
该订单不存在或已过期

### ISSUE THREAD

**Issue by sakura-yuina** [assimon/dujiaoka#181]
无论是当面付渠道还是其他渠道,支付成功后***均*** 提示此消息  
对应错误码 `order_does_not_exist`

> 相关环境  
- PHP 7.3.26
```php
PHP 7.3.26 (cli) (built: Feb  5 2021 03:21:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.26, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.4.1, Copyright (c) 2002-2020, by ionCube Ltd.
```
主要插件有 `ionCube` `fileinfo` `redis` `sg11`  
- 由Screen管理的Laravel队列
启动参数 
```cs
php /var/website/pay/artisan queue:work
``` 
(仅装有一个PHP 7.3.26)

Redis连接正常,数据库连接正常,.env配置贴在下面

```php
APP_NAME=XXXXXXX
APP_ENV=local
APP_KEY=base64:h2OIkeCM46ucrQUFXXXXXXXXXv3u95M9/k5QCxrp4=
APP_DEBUG=true
APP_URL=https://XXX.XXXX.XXX
ADMIN_HTTPS=true
ADMIN_ROUTE_PREFIX=XXXX
ADMIN_SKIN=rainbow-cyan

SH_GEETEST=true
GEETEST_ID=XXXX2c7505eXXXXXXXXXXXXcf99efXXX
GEETEST_KEY=XXXX2a1be87XXXXXXXXXXXX2bef6XXX

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=XXX
DB_USERNAME=XXX
DB_PASSWORD=XXX

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.XXX.com
MAIL_PORT=465
MAIL_USERNAME=XXXX@XX.XXX
MAIL_PASSWORD=XXXXXXXXX

MAIL_FROM_ADDRESS=XXXX@XXX.XXX
MAIL_FROM_NAME=XXXXX
MAIL_ENCRYPTION=ssl

PAYPAL_SANDBOX=false

ORDER_EXPIRE_DATE=30

LOG_CHANNEL=stack
BROADCAST_DRIVER=log
CACHE_DRIVER=redis
QUEUE_CONNECTION=redis
SESSION_DRIVER=file
SESSION_LIFETIME=120

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

**Comment by wexiuwexiu** [comment]
我的也是，我把电脑时区改回中国就没问题了

**Comment by assimon** [comment]
> 无论是当面付渠道还是其他渠道,支付成功后_**均**_ 提示此消息
> 对应错误码 `order_does_not_exist`
> 
> > 相关环境
> 
> * PHP 7.3.26
> 
> ```
> PHP 7.3.26 (cli) (built: Feb  5 2021 03:21:02) ( NTS )
> Copyright (c) 1997-2018 The PHP Group
> Zend Engine v3.3.26, Copyright (c) 1998-2018 Zend Technologies
>     with the ionCube PHP Loader + ionCube24 v10.4.1, Copyright (c) 2002-2020, by ionCube Ltd.
> ```
> 
> 主要插件有 `ionCube` `fileinfo` `redis` `sg11`
> 
> * 由Screen管理的Laravel队列
>   启动参数
> 
> ```cs
> php /var/website/pay/artisan queue:work
> ```
> 
> (仅装有一个PHP 7.3.26)
> 
> Redis连接正常,数据库连接正常,.env配置贴在下面
> 
> ```
> APP_NAME=XXXXXXX
> APP_ENV=local
> APP_KEY=base64:h2OIkeCM46ucrQUFXXXXXXXXXv3u95M9/k5QCxrp4=
> APP_DEBUG=true
> APP_URL=https://XXX.XXXX.XXX
> ADMIN_HTTPS=true
> ADMIN_ROUTE_PREFIX=XXXX
> ADMIN_SKIN=rainbow-cyan
> 
> SH_GEETEST=true
> GEETEST_ID=XXXX2c7505eXXXXXXXXXXXXcf99efXXX
> GEETEST_KEY=XXXX2a1be87XXXXXXXXXXXX2bef6XXX
> 
> DB_CONNECTION=mysql
> DB_HOST=localhost
> DB_PORT=3306
> DB_DATABASE=XXX
> DB_USERNAME=XXX
> DB_PASSWORD=XXX
> 
> REDIS_HOST=127.0.0.1
> REDIS_PASSWORD=null
> REDIS_PORT=6379
> 
> MAIL_DRIVER=smtp
> MAIL_HOST=smtp.XXX.com
> MAIL_PORT=465
> MAIL_USERNAME=XXXX@XX.XXX
> MAIL_PASSWORD=XXXXXXXXX
> 
> MAIL_FROM_ADDRESS=XXXX@XXX.XXX
> MAIL_FROM_NAME=XXXXX
> MAIL_ENCRYPTION=ssl
> 
> PAYPAL_SANDBOX=false
> 
> ORDER_EXPIRE_DATE=30
> 
> LOG_CHANNEL=stack
> BROADCAST_DRIVER=log
> CACHE_DRIVER=redis
> QUEUE_CONNECTION=redis
> SESSION_DRIVER=file
> SESSION_LIFETIME=120
> 
> AWS_ACCESS_KEY_ID=
> AWS_SECRET_ACCESS_KEY=
> AWS_DEFAULT_REGION=us-east-1
> AWS_BUCKET=
> 
> PUSHER_APP_ID=
> PUSHER_APP_KEY=
> PUSHER_APP_SECRET=
> PUSHER_APP_CLUSTER=mt1
> 
> MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
> MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
> ```

参考楼上所诉解决方案试试
