### ISSUE TITLE
支付页面显示500 Server Error

### ISSUE THREAD

**Issue by q845533229** [assimon/dujiaoka#183]
支付页面显示500 Server Error 出现这种情况该怎么办？
![1234](https://user-images.githubusercontent.com/64315111/108148924-c8f55680-710c-11eb-8668-7d770517554a.png)
后台支付配置附上
![12345](https://user-images.githubusercontent.com/64315111/108148987-e3c7cb00-710c-11eb-9db2-b5895cee64b2.png)

**Comment by assimon** [comment]
开debug看具体报错信息
