### ISSUE TITLE
建议：新增管理员邮件接收提醒

### ISSUE THREAD

**Issue by xx599** [assimon/dujiaoka#184]
建议：新增管理员邮件接收提醒功能。
因Server酱试用版每天发送条数有限制，所以建议添加管理员邮件接收提醒功能。
PS:隔壁的发卡系统已经有这个功能了，但我还是喜欢独角的系统。

**Comment by assimon** [comment]
自带管理员邮件提醒啊，你看.env文件或者视频教程
