### ISSUE TITLE
能否支持使用payjs微信支付后自动跳转到微信进行支付

### ISSUE THREAD

**Issue by huang545** [assimon/dujiaoka#185]
扫码支付没有问题，但是如果本身在手机上操作无法使用payjs微信付款，看了一下说明文档，有两种方法，一种是jsapi，另一种是收银台模式，可以支持一下么？

**Comment by assimon** [comment]
后续支持

**Comment by dylanbai8** [comment]
payjs老用户不支持开通h5，，，fuck！
