### ISSUE TITLE
建议支持reCaptcha

### ISSUE THREAD

**Issue by huang545** [assimon/dujiaoka#186]
极验已经完全取消了免费额度，私聊了客服，他表示已经不免费使用了，需要付费，建议支持reCaptcha
在国内有镜像，速度非常快

**Comment by dylanbai8** [comment]
我极验正常用呀，没收到取消通知。你确定？？

**Comment by dylanbai8** [comment]
reCaptcha我博客使用了一个月了。v2版好像需要翻墙，国内能用的是v3版。
但v3版似乎只能防御 脚本、机器人、批量注册，对真人“手工”刷单视而不见。
个人以为reCaptcha对发卡无意义。

**Comment by huang545** [comment]
> reCaptcha我博客使用了一个月了。v2版好像需要翻墙，国内能用的是v3版。
> 但v3版似乎只能防御 脚本、机器人、批量注册，对真人“手工”刷单视而不见。
> 个人以为reCaptcha对发卡无意义。

一个多月了，不理人
recaptcha不需要翻墙，你用的估计是谷歌的网站，替换成recaptcha.net就好了，国内国外都可以用，国内也有节点支持

**Comment by dylanbai8** [comment]
不要抱怨，作者没有回复你的义务。欢迎贡献代码

**Comment by huang545** [comment]
> 不要抱怨，作者没有回复你的义务。欢迎贡献代码

不是不是，没抱怨作者，我是说极验申请了一个多月不理人...
我原本加作者准备看二开价格的，但作者没同意
非伸手党
