### ISSUE TITLE
Mugglepay 支付 Undefined index: payment_url

### ISSUE THREAD

**Issue by xinxin8816** [assimon/dujiaoka#187]
环境里打开了APP_DEBUG，但是前端没有跳到dubug页面

![](https://i.ibb.co/R0Q9mdV/20210222225727.png)

**Comment by assimon** [comment]
@ilay1678

**Comment by assimon** [comment]
https://github.com/assimon/dujiaoka/blob/master/wikis/problems.md#%E5%90%84%E6%94%AF%E4%BB%98%E5%AF%B9%E5%BA%94%E9%85%8D%E7%BD%AE

**Comment by ilay1678** [comment]
> @ilay1678

没遇到这种情况。
app/Http/Controllers/Pay/MugglepayController.php 第33行`$payment_url = json_decode($response, true)['payment_url'];`上面添加dd($response)，看看具体返回的是啥

**Comment by xinxin8816** [comment]
感谢各位大佬，找到原因了
Mugglepay 不支持 IPV6 Only 导致无法通信，用 DNS64 解决了
