### ISSUE TITLE
宝塔安装到最后倒数第二步导入sql时出错

### ISSUE THREAD

**Issue by albertxu1** [assimon/dujiaoka#188]
我在腾讯云的轻量应用服务器安装宝塔，安装到达这一步时/www/server/php/74/bin/php artisan dujiao install 出错，

   UnexpectedValueException  : The stream or file "/usr/local/lighthouse/softwares/btpanel/wwwroot/gold.com/storage/logs/laravel-2021-03-03.log" could not be opened: failed to open stream: Permission denied

请帮忙看一下。
![Snipaste_2021-03-03_08-55-49](https://user-images.githubusercontent.com/19591351/109736310-138fcc00-7bff-11eb-81d6-6cee805e29f0.png)

**Comment by assimon** [comment]
目录没有权限，给对应的目录权限
