### ISSUE TITLE
批量导入卡密的时候空格会消失

### ISSUE THREAD

**Issue by q112664** [assimon/dujiaoka#197]
单个添加的不会消失

**Comment by dylanbai8** [comment]
是这样的。用间隔符代替空格吧，比如 ----

**Comment by mengdwwork** [comment]
老板，这个能解决么？或者代码在哪个位置，我自己改。

**Comment by mengdwwork** [comment]
额  我自己解决了

**Comment by q112664** [comment]
> 额 我自己解决了

老哥，你咋解决的

**Comment by mengdwwork** [comment]
> > 额 我自己解决了
> 
> 老哥，你咋解决的

有个方法，应该是就是去除空格的，我没让他处理，绕过了。

**Comment by q112664** [comment]
> > > 额 我自己解决了
> > 
> > 
> > 老哥，你咋解决的
> 
> 有个方法，应该是就是去除空格的，我没让他处理，绕过了。

老哥，啥方法呀，是改哪个文件吗？
