### ISSUE TITLE
卡密分发的问题

### ISSUE THREAD

**Issue by Nansir0808** [assimon/dujiaoka#198]
跳转到支付页面，未支付在返回，卡密的库存减一，等待三分钟刷新，卡密库存依旧没有恢复。在后台也米有找到未支付的卡密处理的订单，在卡密管理界面也无法分清楚哪些是因为支付不成功而被减库存的卡密。目前测试到的最大的bug吧。如果恶意购买后未支付，非常影响店铺的正常运营。

**Comment by dylanbai8** [comment]
仔细看教程吧，你自己的问题。

**Comment by Nansir0808** [comment]
我把环境，函数禁用，设置都看了一遍，是哪里错了，麻烦兄台指出一下

**Comment by Nansir0808** [comment]
额。。。不好意思，测试了一下，把作者的演示站  请喝咖啡搬空了。。。是3分钟之后就会恢复吗。。。不是故意的啊

**Comment by Nansir0808** [comment]
恢复了，看来是我哪里设置的问题，我找找

**Comment by assimon** [comment]
supervisor多半没有设置正确
