### ISSUE TITLE
想问一下，自动发卡模式怎么设置发邮件通知站长？

### ISSUE THREAD

**Issue by qingxiablog** [assimon/dujiaoka#199]
想问一下，自动发卡模式怎么设置发邮件通知站长？

**Comment by assimon** [comment]
后台设置，填写管理员邮箱即可

**Comment by qingxiablog** [comment]
我是说自动发卡模式，不是代充模式。我测试过自动发卡模式只有server酱可以收到通知，后台的管理邮箱收不到。但代充模式我后台设置的管理邮箱是能收到订单通知的，我这么说您能理解么？是我自己配置的问题么？关键是我在后台的邮件模版里也没看到自动发卡后通知管理员的邮件模版

**Comment by assimon** [comment]
自动发卡不会向管理员发送邮件

**Comment by qingxiablog** [comment]
我想设置成自动发卡模式有订单时给管理员发邮件，没办法设置么？

**Comment by assimon** [comment]
目前除了自己会改代码之外，别无他法
