### ISSUE TITLE
页脚代码会在前台直接输出

### ISSUE THREAD

**Issue by iLay1678** [assimon/dujiaoka#21]
页脚代码没用，目前会在前台直接输出啊，版本1.2beta

**Comment by KLDGodY** [comment]
提供个截图?

**Comment by KLDGodY** [comment]
我昨天搭建的事可以的，，

**Comment by iLay1678** [comment]
![Screenshot_20200419_163933](https://user-images.githubusercontent.com/7021399/79683390-6c12e080-825c-11ea-8616-bca9ccf391f0.jpg)

**Comment by assimon** [comment]
> 页脚代码没用，目前会在前台直接输出啊，版本1.2beta

已经修复
