### ISSUE TITLE
每个支付都能用么  怎么有些支付支付后没有回调啊

### ISSUE THREAD

**Issue by mengdwwork** [assimon/dujiaoka#210]

**Comment by assimon** [comment]
每个支付都能用，没有回调多半是自己配置错了，仔细看支付配置文档

**Comment by mengdwwork** [comment]
你好 我用的paysapi 按照文档的设置了 商户id token 上传了二维码  就是没有回调啊？是我哪里配置错了么？您能给看下么

**Comment by mengdwwork** [comment]
您那边可以么？

**Comment by assimon** [comment]
应该是paysapi的问题，问一下支付商是否有回调？看看回调记录
