### ISSUE TITLE
支付宝当面付异常

### ISSUE THREAD

**Issue by ilinsen** [assimon/dujiaoka#22]
配置好商户id 和商户秘钥以后，付款不出二维码 。显示支付通道异常~！ INVALID_CONFIG: Missing Alipay Config -- [ali_public_key]。再三确认商户id和秘钥没有错误

**Comment by assimon** [comment]
> 配置好商户id 和商户秘钥以后，付款不出二维码 。显示支付通道异常~！ INVALID_CONFIG: Missing Alipay Config -- [ali_public_key]。再三确认商户id和秘钥没有错误

这个是你当面付的支付宝公钥设置错误，可以去群里看当面付的视频教程
