### ISSUE TITLE
我添加商品的时候上传的图片会自动切换指向dujiaoka.com

### ISSUE THREAD

**Issue by beii1122** [assimon/dujiaoka#223]
自动替换成这个了
![_SD1(2AMB C2L V9`D5J1JQ](https://user-images.githubusercontent.com/82789777/116877935-336c5c00-ac51-11eb-84d5-66559ae40e15.png)
http://dujiaoka.com/uploads/images/55b5ac8b48a20b60e86eb77daea46e15.jpg

**Comment by beii1122** [comment]
上传的图片就是随机名称但是指向dujiaoka.com

**Comment by beii1122** [comment]
前台以及后台都不显示商品图片

**Comment by assimon** [comment]
.env里面把域名改成自己的
