### ISSUE TITLE
有没有套了cf cdn的大佬分享下规则,我这里默认支付没返回

### ISSUE THREAD

**Issue by insoxin** [assimon/dujiaoka#226]

**Comment by sduwfc** [comment]
同样遇到这个问题
现在使用的是支付宝当面付支付,防火墙放行了支付宝的ip,现在还是支付后,二维码页面没反应,但是实际已经收到款了

**Comment by insoxin** [comment]
> 同样遇到这个问题
> 现在使用的是支付宝当面付支付,防火墙放行了支付宝的ip,现在还是支付后,二维码页面没反应,但是实际已经收到款了

我换了隔壁zfaka正常,本来是看中独角的,都是一个论坛的,然后bug有点多哈哈哈哈

独角发卡一个问题也许是bug-美国VPS综合讨论-全球主机交流论坛 - Powered by Discuz! https://hostloc.com/thread-844130-1-1.html

**Comment by sduwfc** [comment]
很奇怪,我之前也用独角卡套cf,去年是没有问题的,今年再用就这样了
同样的ripro的支付宝当面付套了cf后也这样
