### ISSUE TITLE
导入sql文件出错

### ISSUE THREAD

**Issue by jizhanqingfeng** [assimon/dujiaoka#229]
导入命令 
/www/server/php/72/bin/php /www/wwwroot/www.xxx.com/artisan dujiao install

运行结果

PHP Warning:  require(/www/wwwroot/www.xxx.com/vendor/autoload.php): failed to open stream: No such file or directory in /www/wwwroot/www.xxx.com/artisan on line 18

Warning: require(/www/wwwroot/www.xxx.com/vendor/autoload.php): failed to open stream: No such file or directory in /www/wwwroot/www.xxx.com/artisan on line 18
PHP Fatal error:  require(): Failed opening required '/www/wwwroot/www.xxx.com/vendor/autoload.php' (include_path='.:/www/server/php/72/lib/php') in /www/wwwroot/www.xxx.com/artisan on line 18

Fatal error: require(): Failed opening required '/www/wwwroot/www.xxx.com/vendor/autoload.php' (include_path='.:/www/server/php/72/lib/php') in /www/wwwroot/www.xxx.com/artisan on line 18

是什么问题呢？小白搞不懂

**Comment by assimon** [comment]
下载带build的压缩包
