### ISSUE TITLE
uc浏览器提交订单异常

### ISSUE THREAD

**Issue by hqsy12345** [assimon/dujiaoka#237]
你好，手机端使用uc浏览器提交订单会提示Whoops，looks like something went wrong，改用小米手机自带的浏览器又没问题，使用得模板是luna，请问这个问题是什么原因导致的，该如何解决，谢谢！

**Comment by assimon** [comment]
打开.env文件里的APP_DEBUG=true  看看具体的错误

**Comment by hqsy12345** [comment]
> 打开.env文件里的APP_DEBUG=true 看看具体的错误

后面又好了，反正我看调试的信息显示什么get,post方法不对之类的东西，当出现这个问题的时候任何使用独角数卡的网站都会这样提示，不仅是我自己的网站

**Comment by assimon** [comment]
好的，这边持续观察一下
