### ISSUE TITLE
导入卡密报500错误

### ISSUE THREAD

**Issue by suguangcheng** [assimon/dujiaoka#252]
导入卡密，提交时提示服务器500错误。
在宝塔面板上查看log，显示：
61.141.64.41 - - [05/Jul/2021:11:15:00 +0800] "POST /admin/dcat-api/form HTTP/1.1" 500 15588 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

**Comment by assimon** [comment]
被宝塔防火墙拦截了，自行放行规则

**Comment by suguangcheng** [comment]
> 被宝塔防火墙拦截了，自行放行规则

能说一下是哪个端口吗？

**Comment by suguangcheng** [comment]
我把1-40000端口号全部放行。导入卡密，提交后，还是会报错
错误log和之前一样。

**Comment by LonelyBoy857** [comment]
拦截的不是端口    放行后台所有路径

**Comment by suguangcheng** [comment]
> 拦截的不是端口 放行后台所有路径

请教，在哪里配置放行后台所有路径?
在宝塔面后台找了一圈也没找到相关的配置
