### ISSUE TITLE
支付通道不可用

### ISSUE THREAD

**Issue by zjh4473** [assimon/dujiaoka#253]
我测试了payjs和微信官方，均不可用。
微信官方的提示：支付网关异常！ERROR_GATEWAY: Get Wechat API Error:无法将输入源“/body/xml/total_fee”映射到目标字段“标价金额”中，此字段需要一个合法的 64 位有符号整数
Payjs的也有错误我没记录信息

后台支付配置页面也有毛病，
这就是个残次品。

**Comment by assimon** [comment]
微信和payjs已经解决。残次品不会用不要用
