### ISSUE TITLE
BUG提交

### ISSUE THREAD

**Issue by UserZHTW** [assimon/dujiaoka#254]
2.0的BUG
1.语言修改成其他语言只会在管理后台显示，其他还是简体中文
2.语言更换只能透过.env更改，即使上传了新语言包管理后台只会有简体中文
3.商品价格设置假如要输入8.5，直接键盘输入会写88.55，无法输入8.5，只能透过复制贴上修改

其他建议反馈
【以下随便看看就好，只是几个自己的想法不是需求，也不用针对以下回复】

建议既然都使用PayPal以及多语言功能作为其他国家用户支付，
建议新增货币功能，例如可以设置发卡站主要使用货币为USD、HKD则一选择等等..
汇率也可以自行设置

不然有了语言功能货币没有有点奇怪

**Comment by assimon** [comment]
后台管理跟前端的语言包是分开的

**Comment by UserZHTW** [comment]
> 后台管理跟前端的语言包是分开的
前台没有配置语言包么？我找了带有zh_cn的文档地址没有找到其它其他语言的存放路径
