### ISSUE TITLE
订单下拉错位

### ISSUE THREAD

**Issue by UserZHTW** [assimon/dujiaoka#255]
1.
![jpg](https://user-images.githubusercontent.com/10895152/125336993-03dc7d00-e381-11eb-8c9f-549948845617.jpg)

2.
![02](https://user-images.githubusercontent.com/10895152/125337443-954bef00-e381-11eb-8265-c12f3998b246.jpg)

上传图片按钮时常消失，导致无法上传，拖拉图片上传也失效

**Comment by assimon** [comment]
最新版本已修复
