### ISSUE TITLE
修改¥为$，但不显示

### ISSUE THREAD

**Issue by UserZHTW** [assimon/dujiaoka#257]
![02](https://user-images.githubusercontent.com/10895152/125406347-50f53900-e3eb-11eb-8437-feed28bd03a2.jpg)
![02](https://user-images.githubusercontent.com/10895152/125406571-8d289980-e3eb-11eb-85ac-4b6e30a4e266.jpg)
![02](https://user-images.githubusercontent.com/10895152/125406706-b47f6680-e3eb-11eb-93db-20ea671698a8.jpg)
![02](https://user-images.githubusercontent.com/10895152/125406860-dd076080-e3eb-11eb-9163-9e310fdcc1ff.jpg)

**Comment by assimon** [comment]
已修复
