### ISSUE TITLE
V免签，Route [vpay-return] not defined.

### ISSUE THREAD

**Issue by ayden97** [assimon/dujiaoka#259]
![image](https://user-images.githubusercontent.com/60477884/125571600-afa778cd-a573-4736-880b-f3ad8543a33f.png)
修改完这两处回去之后就没问题了，但是支付完成出现跳转bug

![image](https://user-images.githubusercontent.com/60477884/125571663-dd095832-152a-4705-868f-4a70921428f4.png)
![image](https://user-images.githubusercontent.com/60477884/125571676-72598fd7-5c86-419d-b32f-fd623f85cff4.png)

**Comment by assimon** [comment]
什么bug我没理解

**Comment by ayden97** [comment]
> 什么bug我没理解
  就是对接v免签在支付时候出现了 “Route [vpay-return] not defined. ”
![image](https://user-images.githubusercontent.com/60477884/125580312-d9394ad6-aacb-4108-83fc-242c24a4657e.png)
