### ISSUE TITLE
关于Mugglepay的payGateway->merchant_id 问题

### ISSUE THREAD

**Issue by CreadwordGOD** [assimon/dujiaoka#261]
版本2.0.0.beta
Mugglepay已取消商户ID并仅提供密钥
而独角的token取的是merchant_id. 导致400错误.(用户也找不到商户ID是多少)
建议取消merchant_id 并将 $this->payGateway->merchant_id 改为 $this->payGateway->merchant_pem
即可使用

**Comment by assimon** [comment]
@ilay1678
