### ISSUE TITLE
建议打包个Docker吧，这样部署也方便

### ISSUE THREAD

**Issue by tzchz** [assimon/dujiaoka#263]
建议打包成Docker环境
一则部署方便，docker run 一句话就行了
二则兼容性好，不会因为系统版本等问题有奇奇怪怪的错误
三则隔离性高，如果有其他站点在同一主机上运行互不影响
四则可迁移性也好

**Comment by assimon** [comment]
在考虑这个事情

**Comment by railwcode** [comment]
铜球，感谢作者老哥

**Comment by Qlmuby** [comment]
龟球，感谢作者老哥，同时问一下如何升级版本，现在用的2.0版本，如何升级到最新版本，1.x升级2.0为保险起见是重新部署的，2.0后续升级要怎么弄

**Comment by assimon** [comment]
https://github.com/assimon/dujiaoka/wiki/docker_install
由第三方贡献者提供

**Comment by kanadeblisst** [comment]
希望docker能将mysql、redis的配置独立出来，不是创建一个mysql容器

**Comment by JiangJuHong** [comment]
> 希望docker能将mysql、redis的配置独立出来，不是创建一个mysql容器

![image](https://user-images.githubusercontent.com/17740963/147798916-2d659f8b-52e5-4acd-b672-71f91496f65e.png)
![image](https://user-images.githubusercontent.com/17740963/147798923-2cb4adbe-c762-425f-9fad-0158009fb08b.png)
编写你的环境配置即可
