### ISSUE TITLE
增加拍下不付款记录ip行为防止捣乱

### ISSUE THREAD

**Issue by zxc2590126260** [assimon/dujiaoka#265]
现在遇到一种情况假如说某个时间段 商品买的很火 库存有100个 但是有一个捣乱的人来 就盯着这个时间段 一次性拍下100个不付款
然后一直重复这个操作 每天都来 后台也不知道到底是哪个IP 到底是谁 
虽然说订单过期后会自动恢复 但是他就在这个页面守着 或者写一个自动化脚本 可以让整个卡网 连续一个月没有库存

**Comment by zxc2590126260** [comment]
目前遇到这种可以说 无解除非拉黑他的IP 唯一解决办法

**Comment by hqsy12345** [comment]
> 目前遇到这种可以说 无解除非拉黑他的IP 唯一解决办法

2.0版本会显示下单ip，直接把ip拉黑不让访问网站试试

**Comment by zxc2590126260** [comment]
或增加单IP一次性最大购买数量 以及购买间隔限制

**Comment by assimon** [comment]
2.0有限制单次最大购买数量，而且2.0下单不减库存。付款成功后才减去库存。就是为了防止这样的事件发生
