### ISSUE TITLE
发现一个问题2.0版本导出卡密默认是没有phpzip扩展的

### ISSUE THREAD

**Issue by zxc2590126260** [assimon/dujiaoka#266]
2.0版本导出卡密默认是没有phpzip扩展的
会报错Symfony\Component\Debug\Exception\FatalThrowableError
Class 'ZipArchive' not found
![image](https://user-images.githubusercontent.com/30953213/126602092-a9293df4-87e0-45bb-8820-33016001c877.png)
 不确定是不是我的问题
如果不是 建议教程里面特别说明一下 还要安装php的zip扩展

**Comment by assimon** [comment]
好的  收到反馈 谢谢
