### ISSUE TITLE
2.0 购买提示不弹出

### ISSUE THREAD

**Issue by LaoFang1s** [assimon/dujiaoka#267]
2.0 购买提示 不弹出 ，网站公告没问题。luna主题

**Comment by LaoFang1s** [comment]
> 2.0 购买提示 不弹出 ，网站公告没问题。luna主题

原来是不能换行，换行就会不弹窗，只能一行。

**Comment by LaoFang1s** [comment]
> > 2.0 购买提示 不弹出 ，网站公告没问题。luna主题
> 
> 原来是不能换行，换行就会不弹窗，只能一行。1.8.2没这个问题，2.0网站公告也没这个问题。

研究一个方法是：编辑的时候 换行用</br>代替，然后保存，然后再进入编辑，发现</br>不见了，不要管他，直接点保存。

**Comment by LaoFang1s** [comment]
最好还是希望修下代码

**Comment by assimon** [comment]
已经反馈模板作者。
@Julyssn

**Comment by c939984606** [comment]
最好还是希望修下代码

**Comment by assimon** [comment]
我本地测试并没有发现这个问题
![image](https://user-images.githubusercontent.com/35057561/127080176-f83b5a38-5fa4-4ad2-8c29-6585fac915f1.png)

**Comment by c939984606** [comment]
> 我本地测试并没有发现这个问题
> ![image](https://user-images.githubusercontent.com/35057561/127080176-f83b5a38-5fa4-4ad2-8c29-6585fac915f1.png)

你有开极验证吗

**Comment by LaoFang1s** [comment]
> > 我本地测试并没有发现这个问题
> > ![image](https://user-images.githubusercontent.com/35057561/127080176-f83b5a38-5fa4-4ad2-8c29-6585fac915f1.png)
> 
> 你有开极验证吗

没开极验~

**Comment by assimon** [comment]
已修复，请下载最新安装包
