### ISSUE TITLE
下单页填写资料框内的提醒在哪修改？

### ISSUE THREAD

**Issue by baiguke2019** [assimon/dujiaoka#268]
![微信截图_20210725131829](https://user-images.githubusercontent.com/44437213/126888627-f1cc0972-6be2-4257-a7c4-ced2162f6e60.png)

**Comment by LaoFang1s** [comment]
项目/resources/views/主题文件夹/static_pages/buy.blade.php
![image](https://user-images.githubusercontent.com/44582189/126891131-1145401f-fa6c-4dc1-9ebd-a16c46e54a66.png)

**Comment by baiguke2019** [comment]
> 项目/resources/views/主题文件夹/static_pages/buy.blade.php
> ![image](https://user-images.githubusercontent.com/44582189/126891131-1145401f-fa6c-4dc1-9ebd-a16c46e54a66.png)

非常感谢😘😘
