### ISSUE TITLE
订单列表显示问题

### ISSUE THREAD

**Issue by LaoFang1s** [assimon/dujiaoka#269]
排版问题能否改进一下
![image](https://user-images.githubusercontent.com/44582189/127021027-ba493d28-5d84-45df-bf7b-a361b0e4d9cc.png)

**Comment by assimon** [comment]
没有什么问题，自适应的，列表有这么长没办法

**Comment by LaoFang1s** [comment]
> 没有什么问题，自适应的，列表有这么长没办法

我意思 可以加个左右滚动条 不然看起来很费劲呢
