### ISSUE TITLE
编辑订单 2.0

### ISSUE THREAD

**Issue by alvincheang** [assimon/dujiaoka#271]
请问2.0版本是不是没了编辑订单的选项？
以前1.8有。
有时候人工发货的需要把发货资料编辑在订单里 （顾客可以查询订单的时候查询到）. 这个功能还会再有吗？

**Comment by LaoFang1s** [comment]
同问，建议增加编辑功能

**Comment by zxmlysxl** [comment]
这是基本功能，期待早日恢复

**Comment by assimon** [comment]
已恢复该功能，等待下次发布。
https://github.com/assimon/dujiaoka/commit/2d86b6988ce2e18a1794787f4ff4f02db680d6d9

**Comment by alvincheang** [comment]
好的，刚刚尝试用最新的order controller.php 覆盖试下功能，有以下错误。等大大发布稳定更新呗 谢谢你:)
[Illuminate\Database\QueryException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'type' cannot be null (SQL: update `orders` set `type` = ?, `info` = 自定义前缀:tyu 1234, `status` = 4, `orders`.`updated_at` = 2021-07-28 10:45:25 where `id` = 4)

**Comment by assimon** [comment]
> 好的，刚刚尝试用最新的order controller.php 覆盖试下功能，有以下错误。等大大发布稳定更新呗 谢谢你:)
> [Illuminate\Database\QueryException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'type' cannot be null (SQL: update `orders` set `type` = ?, `info` = 自定义前缀:tyu 1234, `status` = 4, `orders`.`updated_at` = 2021-07-28 10:45:25 where `id` = 4)

这是你自己替换的问题，如果不会看git commit记录建议等下次发版

**Comment by assimon** [comment]
> 好的，刚刚尝试用最新的order controller.php 覆盖试下功能，有以下错误。等大大发布稳定更新呗 谢谢你:)
> [Illuminate\Database\QueryException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'type' cannot be null (SQL: update `orders` set `type` = ?, `info` = 自定义前缀:tyu 1234, `status` = 4, `orders`.`updated_at` = 2021-07-28 10:45:25 where `id` = 4)
已修复，参考这条记录
https://github.com/assimon/dujiaoka/commit/64b96da4d6fc3ca3482d8986adf14261ef6ae8c6

**Comment by alvincheang** [comment]
可以了 谢谢大大 ^.^
