### ISSUE TITLE
Payjs 微信扫码支付网关异常

### ISSUE THREAD

**Issue by DavidNi666** [assimon/dujiaoka#276]
1.82正常调用

2.0无法使用提示如下：

支付网关异常！Method App\Http\Controllers\Pay\PayjsController::view does not exist.

**Comment by fengtalk** [comment]
支付网关异常！Method App\Http\Controllers\Pay\PayjsController::view does not exist.
+1

**Comment by assimon** [comment]
已经解决这个bug，等待下次打包发版，目前着急使用的请大家先参考这条变更记录手动修复https://github.com/assimon/dujiaoka/commit/c191be8099afde5fdff3c0e27143cb29ff37b25a

**Comment by DavidNi666** [comment]
已修复，测试ok，感谢

**Comment by assimon** [comment]
我重新打开了，说不定后面的人需要这个问题
