### ISSUE TITLE
2.0.0 宝塔安装提示 发生错误: undefined

### ISSUE THREAD

**Issue by zhucaidan** [assimon/dujiaoka#277]
2.0.0-Antibody 宝塔安装提示 发生错误: undefined
环境均按照教程操作的

![image](https://user-images.githubusercontent.com/47970938/127744172-b22e9cf3-b7fd-4bf4-83c1-31b1929757f1.png)

**Comment by assimon** [comment]
无法得知具体错误，能抓包吗

**Comment by zhucaidan** [comment]
> 无法得知具体错误，能抓包吗

目前已解决，是安装时候开启https导致的，关掉ssl后安装然后再开启就好了

**Comment by wltc2005** [comment]
遇到了同样的问题，确实如楼主说描述，作者没考虑https的情况。
