### ISSUE TITLE
发现bug

### ISSUE THREAD

**Issue by Ambitions2** [assimon/dujiaoka#278]
模板 luna

**Comment by Ambitions2** [comment]
![1A1EF0B47AC26D15E6DF4E46F883D367](https://user-images.githubusercontent.com/88265254/127762035-9abcf33a-72d7-4db6-a956-7790e097c3e1.png)
![983C19FED11C22A4FDCD6EC769454834](https://user-images.githubusercontent.com/88265254/127762037-cdde122d-097b-4cd4-aa20-a5575717a880.png)

**Comment by Ambitions2** [comment]
下单的时候输入信息 到确认订单的时候 所有填的信息都会变成一样的

**Comment by Ambitions2** [comment]
@Julyssn @assimon

**Comment by assimon** [comment]
你规则配置错了吧，截图代充框配置

**Comment by Ambitions2** [comment]
![UTQ74KT9`3ZG7V3T_FLH2Q6](https://user-images.githubusercontent.com/88265254/127805594-15839f20-a032-480b-a81f-fa14169e9000.png)

**Comment by Ambitions2** [comment]
![5P$JY%U~EE)5DV@F$2OXGP4](https://user-images.githubusercontent.com/88265254/127805848-58880872-64e5-4929-80a4-1c5d7404cf2b.png)
改成这样就好了 多谢大大 一语惊醒梦中人   完全按1.8的操作了
