### ISSUE TITLE
优惠码BUG

### ISSUE THREAD

**Issue by rvvcim** [assimon/dujiaoka#280]
优惠码设置的是3次可用，然而实际提交了4个订单？

![i](https://www.gejiba.com/view.php/09ceb4d591591dd94064d3b78b447ebf.jpg)
![ii](https://www.gejiba.com/view.php/84c31d47b4fb5eba58634bb5c56b5164.jpg)

**Comment by assimon** [comment]
订单支付过期会自动回退优惠码次数，你有没有手动操作已过期订单为  其他状态

**Comment by rvvcim** [comment]
这四个订单都是提交成功的诶

**Comment by assimon** [comment]
容我排查看看

**Comment by assimon** [comment]
我没有复现这个问题，暂时先保留这个问题，再观察看看是否会复现。
