### ISSUE TITLE
安装完成后,登录后台时报错

### ISSUE THREAD

**Issue by zhiqiuchn** [assimon/dujiaoka#283]
登录后台时,用户名和密码输入admin后,点登录后,右上角弹出了一个0error红色框提示

**Comment by LaoFang1s** [comment]
> 登录后台时,用户名和密码输入admin后,点登录后,右上角弹出了一个0error红色框提示

![image](https://user-images.githubusercontent.com/44582189/128203303-23e8f435-2bd3-4c68-a56e-1b5a86d2ae51.png)
你这wiki里有，.env文件配置里 加一行 ADMIN_HTTPS=true
