### ISSUE TITLE
人工处理的订单，邮件通知是不含订单详情

### ISSUE THREAD

**Issue by LaoFang1s** [assimon/dujiaoka#284]
人工处理的订单，编辑订单详情后，点已处理，邮件通知是不含订单详情的吗？用户只能通过查订单来查看是吧？
邮件模板 加 ord_info 没效果
需要改什么可以加？
![image](https://user-images.githubusercontent.com/44582189/128203648-c0825619-3367-4f14-bad6-d6637d04b61d.png)

**Comment by assimon** [comment]
下个版本会加上
