### ISSUE TITLE
2.0 paypal 报错400

### ISSUE THREAD

**Issue by LaoFang1s** [assimon/dujiaoka#287]
支付时报错
Got Http response code 401 when accessing https://api.paypal.com/v1/oauth2/token
同样配置，在旧版上可以。

**Comment by assimon** [comment]
检查配置是否正确
https://github.com/assimon/dujiaoka/wiki/problems#%E5%90%84%E6%94%AF%E4%BB%98%E5%AF%B9%E5%BA%94%E9%85%8D%E7%BD%AE

**Comment by LaoFang1s** [comment]
> 检查配置是否正确
> https://github.com/assimon/dujiaoka/wiki/problems#%E5%90%84%E6%94%AF%E4%BB%98%E5%AF%B9%E5%BA%94%E9%85%8D%E7%BD%AE

同样配置 1.8.2上沙箱测试可以

**Comment by assimon** [comment]
2.0填写正式商户，2.0没有沙箱，V2的api

**Comment by LaoFang1s** [comment]
> > 检查配置是否正确
> > https://github.com/assimon/dujiaoka/wiki/problems#%E5%90%84%E6%94%AF%E4%BB%98%E5%AF%B9%E5%BA%94%E9%85%8D%E7%BD%AE
> 
> 同样配置 1.8.2上沙箱测试可以

![image](https://user-images.githubusercontent.com/44582189/128457456-02a9c437-40fe-4f77-97f5-9d5c046c5f10.png)
![image](https://user-images.githubusercontent.com/44582189/128457561-d5455d66-9f54-4b33-98bc-e05e77a5c30d.png)
![image](https://user-images.githubusercontent.com/44582189/128457651-591b5a39-bf46-4598-95ca-b2d14050fe59.png)
![image](https://user-images.githubusercontent.com/44582189/128457761-fe8705cb-bd6d-4ed4-bd57-fda003e30fc0.png)
大佬指点 哪里问题

**Comment by assimon** [comment]
配置文档已更新，应该是我文档写错了误导你们了，看最新的文档配置
https://github.com/assimon/dujiaoka/wiki/problems#%E5%90%84%E6%94%AF%E4%BB%98%E5%AF%B9%E5%BA%94%E9%85%8D%E7%BD%AE

**Comment by jakkpop** [comment]
题主弄好了吗？不过都填写好后，用的live，但还是会显示
GOT HTTP RESPONSE CODE 400 WHEN ACCESSING HTTPS://API.PAYPAL.COM/V1/PAYMENTS/PAYMENT.
这个是什么问题呢？

**Comment by LaoFang1s** [comment]
> 题主弄好了吗？不过都填写好后，用的live，但还是会显示
> GOT HTTP RESPONSE CODE 400 WHEN ACCESSING [HTTPS://API.PAYPAL.COM/V1/PAYMENTS/PAYMENT](HTTPS://API.PAYPAL.COM/V1/PAYMENTS/PAYMENT).
> 这个是什么问题呢？

这是个新问题，我也遇到了，比较奇怪的是，修改商品价格后又正常了，价格改回去又报错400。。

**Comment by jakkpop** [comment]
> > 题主弄好了吗？不过都填写好后，用的live，但还是会显示
> > GOT HTTP RESPONSE CODE 400 WHEN ACCESSING [HTTPS://API.PAYPAL.COM/V1/PAYMENTS/PAYMENT](HTTPS://API.PAYPAL.COM/V1/PAYMENTS/PAYMENT).
> > 这个是什么问题呢？
> 
> 这是个新问题，我也遇到了，比较奇怪的是，修改商品价格后又正常了，价格改回去又报错400。。

可以确定就是bug了，zafaka是可以的

**Comment by LaoFang1s** [comment]
> 配置文档已更新，应该是我文档写错了误导你们了，看最新的文档配置
> https://github.com/assimon/dujiaoka/wiki/problems#%E5%90%84%E6%94%AF%E4%BB%98%E5%AF%B9%E5%BA%94%E9%85%8D%E7%BD%AE

paypal有个新问题，比较奇怪了。群里几个都遇到了。报错400

**Comment by thefreelight** [comment]
请问问题解决了吗，各位大佬

**Comment by LaoFang1s** [comment]
没有吧

**Comment by LaoFang1s** [comment]
> 请问问题解决了吗，各位大佬

没有吧

**Comment by thefreelight** [comment]
> > 请问问题解决了吗，各位大佬
> 
> 没有吧
那就是PayPal用不了了？我在别的程序里PayPal是正常的

**Comment by LaoFang1s** [comment]
> > 请问问题解决了吗，各位大佬
> 
> 没有吧 那就是PayPal用不了了？我在别的程序里PayPal是正常的

是的，在别的发卡正常，独角会报错400，运气好偶尔不报错。
