### ISSUE TITLE
使用美元计价的Stripe发现货币转换的问题

### ISSUE THREAD

**Issue by BlueSkyXN** [assimon/dujiaoka#289]
根据几次测试，可以发现固定为 1USD=6.66CNY 的汇率将标价的人民币转换为美元再推送微信等支付平台用人民币付款美元
而实际上目前汇率大概是 1USD=6.47CNY
我想知道6.66这个汇率是Stripe的操作还是发卡系统的操作，是 预先设定值吗？
后续可否自定义汇率？或者加入全局美元计价功能

**Comment by assimon** [comment]
获取汇率失败就会使用预设6.66
