### ISSUE TITLE
覆盖昨天更新的显示订单内容好像有点bug了。

### ISSUE THREAD

**Issue by qihaimi** [assimon/dujiaoka#290]
覆盖昨天update:增加人工处理后，订单邮件可显示订单内容
在回复的邮件里添加{ord_info}，测试后是可以显示订单内容的，
但是这个{created_at}好像失效了，时间不显示了。

**Comment by alvincheang** [comment]
但我这里没问题

**Comment by qihaimi** [comment]
> 但我这里没问题

奇怪，我这明明有{created_at}，打开邮件里关于{created_at}这行却是空白的

**Comment by qihaimi** [comment]
![image](https://user-images.githubusercontent.com/51589254/128600592-48de4134-be38-4bf0-849b-46e834307a8e.png)

有{created_at}呀。。

**Comment by qihaimi** [comment]
![image](https://user-images.githubusercontent.com/51589254/128601018-97979a40-1c04-4bc9-b85a-476e6f4bf654.png)
感觉没问题呀。。邮件里就是没有这个时间。。

**Comment by alvincheang** [comment]
{created_at}不应该有太大问题才对啊
因为本来没改之前一直都有create at不是？
反正我这里是没问题啦 我也是只是替换那两个php 然后模板加ord info 一切没问题

**Comment by qihaimi** [comment]
> {created_at}不应该有太大问题才对啊
> 因为本来没改之前一直都有create at不是？
> 反正我这里是没问题啦 我也是只是替换那两个php 然后模板加ord info 一切没问题

![image](https://user-images.githubusercontent.com/51589254/128601546-267124a4-8c9c-4c6c-b268-db0354b7baa3.png)
我把这三个更新的php全都替换了。
https://github.com/assimon/dujiaoka/commits/master

**Comment by LaoFang1s** [comment]
> ![image](https://user-images.githubusercontent.com/51589254/128600592-48de4134-be38-4bf0-849b-46e834307a8e.png)
> 
> 有{created_at}呀。。

样式不对吧，自己改错了估计，参考下满这段，注意{order_id}后面的
订单号: {order_id}<br style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />{created_at}<br style="font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; box-sizing: border-box; font-size: 14px; margin: 0;" />以下是您的卡密信息：.....

**Comment by qihaimi** [comment]
> > ![image](https://user-images.githubusercontent.com/51589254/128600592-48de4134-be38-4bf0-849b-46e834307a8e.png)
> > 有{created_at}呀。。
> 
> 样式不对吧，自己改错了估计，参考下满这段，注意{order_id}后面的
> ![image](https://user-images.githubusercontent.com/44582189/128605189-f2ae402b-8fe9-4fa3-80eb-454d417808ad.png)

![image](https://user-images.githubusercontent.com/51589254/128629605-e7795fd7-aedb-4991-a2b7-e312664feeab.png)
![image](https://user-images.githubusercontent.com/51589254/128629616-8c9a4f8e-db79-4c9a-a218-b5adace93f70.png)

就很邪门。。。

**Comment by LaoFang1s** [comment]
> 但我这里没问题

是自动发货的邮件没时间，其他有。

**Comment by LaoFang1s** [comment]
> ![image](https://user-images.githubusercontent.com/51589254/128601018-97979a40-1c04-4bc9-b85a-476e6f4bf654.png)
> 感觉没问题呀。。邮件里就是没有这个时间。。
我看了一下，确实，是自动发货的邮件没时间，其他的邮件有。

**Comment by qihaimi** [comment]
> > ![image](https://user-images.githubusercontent.com/51589254/128601018-97979a40-1c04-4bc9-b85a-476e6f4bf654.png)
> > 感觉没问题呀。。邮件里就是没有这个时间。。
> > 我看了一下，确实，是自动发货的邮件没时间，其他的邮件有。而且 不是修改了才没有的，我翻了下过往邮件，2.0一开始就没有。

噢噢，看来是个小bug，我还以为被自己折腾的。
