### ISSUE TITLE
暂时不支持php8.0和mysql8.0吗？

### ISSUE THREAD

**Issue by zhujitop** [assimon/dujiaoka#294]
php和mysql都是8.0的，访问网站500错误。

是还不支持？

安装页面正常，也提示已经安装好了。
然后访问首页就错误了，好像数据库被拒绝了？
后台管理员登录的时候也是提示500错误。

显示：
`Illuminate\Database\QueryException
SQLSTATE[HY000] [1045] Access denied for user 'root'@'127.0.0.1' (using password: YES) (SQL: select * from `goods_group` where `is_open` = 1 and `goods_group`.`deleted_at` is null order by `ord` desc) `

**Comment by assimon** [comment]
php8和mysql8暂时没测试，建议使用稳定版php7.4和mysql5.7。没必要追求最新，稳定就好
