### ISSUE TITLE
V免签回调失败，貌似与Cloudflare的SSL证书有关，急求解决方案

### ISSUE THREAD

**Issue by Damiey** [assimon/dujiaoka#299]
试过各种方案，只要在 Cloudflare 开启了 SSL/TLS 加密(灵活)，就无法正常回调
具体表现是 收款完毕会跳转，但显示未支付，V免签后台显示通知错误，点进去显示异步通知返回错误，返回数据为false
我试过隔壁红x云卡是不存在这个问题的，但是不套cf也不显示，求解决方案
证书为 Cloudflare 默认的 Let's Encrypt

注：电报其他人套了cf的没有我这个问题，我试过一天了都不行，除非关SSL/TLS 加密

**Comment by huangfengye** [comment]
cf防火墙---工具----IP规则，里面把你的V免签IP加白名单

**Comment by huangfengye** [comment]
最后卡网和V免签在一个服务器
