### ISSUE TITLE
邮件模板BUG  字段 webname  获取的是文字logo字段，不是前台网站标题

### ISSUE THREAD

**Issue by wangegou** [assimon/dujiaoka#302]
![image](https://user-images.githubusercontent.com/50771267/130325824-2f1aa327-8cd9-4721-b671-a89a6429671a.png)
![image](https://user-images.githubusercontent.com/50771267/130325849-b0c6ac30-80bb-402f-b2e4-bd4ec11a476d.png)
![image](https://user-images.githubusercontent.com/50771267/130325859-61d1efe8-855b-4a2d-ac4a-2571078dd515.png)

希望修复

**Comment by wangegou** [comment]
据电报群友反馈，这个webname 是对文字logo字段生效，经测试，确实是这样，希望大佬给修复一下，感谢

**Comment by wangegou** [comment]
![image](https://user-images.githubusercontent.com/50771267/130340223-805a4cfb-8c49-4dd8-b606-065c1ea255ed.png)
自发发货邮件模板，时间未生效

**Comment by wangegou** [comment]
商品名		{product_name}
数量			 {buy_amount}

在手动发货，邮件模板未生效

**Comment by assimon** [comment]
邮件标题取得是.env里面的网站标题，我没有填写再邮件模板里面的变量就是没有，并非没有生效

**Comment by wangegou** [comment]
env里改了之后，会使原来的设置全部丢失

**Comment by assimon** [comment]
改成redis缓存配置就不会丢失了
