### ISSUE TITLE
页脚自定义代码，不能生效或者失效

### ISSUE THREAD

**Issue by wangegou** [assimon/dujiaoka#307]
F12后，我发现JS里的http请求，变成了https，不知道为什么。
![image](https://user-images.githubusercontent.com/50771267/130380869-3c9398cb-87d9-4a7c-9699-a7481ad5e8de.png)

**Comment by wangegou** [comment]
后台设置的JS插入不了页面,所有我吧代码放到_script.blade.php里面了

**Comment by wangegou** [comment]
暂时通过将请求的网站也配置ssl证书把请求https的问题解决了，但是后台自定义代码不能生效还是没有解决，

**Comment by assimon** [comment]
这个应该是你自己配置的问题或者cdn的问题
