### ISSUE TITLE
luna库存绿条显示不对

### ISSUE THREAD

**Issue by GreenTeodoro839** [assimon/dujiaoka#310]
当库存等于销量时，绿条没有了。库存销量比较大时(例如库存80销量132)，绿条就是默认的40%。据说目前是库存除以销量再减一，导致出现负数。建议改成库存÷(库存＋销量)

**Comment by assimon** [comment]
https://github.com/assimon/dujiaoka/commit/c5565b00e65f5e819199e55be80b18633f7d3759
参考这条修复

**Comment by GreenTeodoro839** [comment]
修改以后如果销量为0，绿条就不显示了

**Comment by assimon** [comment]
https://github.com/assimon/dujiaoka/commit/86df875decd146e6b8bc240ff3119c7149d79d31
参考修复
