### ISSUE TITLE
stripe 微信USD结算，而支付宝CNY结算

### ISSUE THREAD

**Issue by Fandshu** [assimon/dujiaoka#312]
如题，微信是转成了USD发给stripe的，支付宝就是直接发CNY让stripe转，stripe转汇有额外手续费。
把StripeController.php的  363-364行：
            amount: $amount,
            currency: 'cny',
修改为：
            amount: $usd,
            currency: 'usd',
支付变为美元结算，但回调500，请问还需要改哪里的代码呢？

**Comment by assimon** [comment]
自行修改代码不接受Issues支持
