### ISSUE TITLE
luna模板商品无法显示BUG反馈

### ISSUE THREAD

**Issue by liuxing01** [assimon/dujiaoka#313]
![20210829](https://user-images.githubusercontent.com/35096100/131229191-69086e11-650b-4e67-8b89-bdaf5ea22cd4.png)

1、luna模板商品无法显示出来，且商品分类也无法选择(包括打开网站后也不会自动选择第一个商品分类)，正常的选择下则会显示蓝色背景；
2、包括页面右侧的手机下单也无法显示；

打开控制台后，发现http://域名xxx/assets/luna/main.js这个js报错了，不知道是不是和这个有关

**Comment by assimon** [comment]
刷新一下浏览器缓存

**Comment by liuxing01** [comment]
解决了，CDN的问题
