### ISSUE TITLE
优化completedOrder订单成功方法 ？

### ISSUE THREAD

**Issue by huangfengye** [assimon/dujiaoka#316]
```cpp 
 public function completedOrder(string $orderSN, float $actualPrice, string $tradeNo = '')
................................
$bccomp = bccomp($order->actual_price, $actualPrice, 2);
            // 金额不一致
            if ($bccomp != 0) {
                throw new \Exception(__('dujiaoka.prompt.order_inconsistent_amounts'));
            }
```

completedOrder传入的$order->actual_price 是商品应支付金额，但是有时候我们可能会给金额价格额外的手续费，导致实际支付金额大于商品应支付金额，所以有没有可能把 $bccomp != 0   改成$bccomp == 1

判断只要$order->actual_price 比 $actualPrice小就行了。

**Comment by assimon** [comment]
你所说的“导致实际支付金额大于商品应支付金额”只存在于V免签，码支付这样的特殊免签支付。我个人认为没有必须去改，如果确实影响使用了可以自行修改

**Comment by huangfengye** [comment]
> 你所说的“导致实际支付金额大于商品应支付金额”只存在于V免签，码支付这样的特殊免签支付。我个人认为没有必须去改，如果确实影响使用了可以自行修改

我自己对接了个数字货币的，这些数字货币一般需要在原价格上加上手续费 ，这些手续费通常较高。😂主要是我自己改的话，每次更新都要改一次代码嫌麻烦，所以跑来问问哈哈

**Comment by assimon** [comment]
可以看看对方支付除了返回真实价格，还有没有原价格，如果有原价格就直接使用原价格
