### ISSUE TITLE
最新提交的修复luna显示bug有问题

### ISSUE THREAD

**Issue by GreenTeodoro839** [assimon/dujiaoka#318]
修改后，如果销量为0，也就是i.sales_volume为0，而使用了&&导致i.sales_volume为false(0)时，直接返回了i.sales_volume(0)，绿条消失。测试发现删除&&和i.sales_volume之后就正常显示了

**Comment by assimon** [comment]
https://github.com/assimon/dujiaoka/commit/86df875decd146e6b8bc240ff3119c7149d79d31
已修复，感谢
