### ISSUE TITLE
Supervisor 報錯

### ISSUE THREAD

**Issue by pinsecode** [assimon/dujiaoka#319]
[2021-09-02 22:27:02][0Z4x7YqTDL5q6x0VS0dzv4IAVVARNTSa] Processing: App\Jobs\SendMails
PHP Fatal error:  method_exists(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition "App\Jobs\SendMails" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition in /home/XXXXX.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php on line 80

   Symfony\Component\Debug\Exception\FatalErrorException  : method_exists(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition "App\Jobs\SendMails" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition

  at /home/XXXXX.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:80
    76|      */
    77|     protected function dispatchThroughMiddleware(Job $job, $command)
    78|     {
    79|         return (new Pipeline($this->container))->send($command)
  > 80|                 ->through(array_merge(method_exists($command, 'middleware') ? $command->middleware() : [], $command->middleware ?? []))
    81|                 ->then(function ($command) use ($job) {
    82|                     return $this->dispatcher->dispatchNow(
    83|                         $command, $this->resolveHandler($job, $command)
    84|                     );

   Whoops\Exception\ErrorException  : method_exists(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition "App\Jobs\SendMails" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition

  at /home/XXXXX.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:80
    76|      */
    77|     protected function dispatchThroughMiddleware(Job $job, $command)
    78|     {
    79|         return (new Pipeline($this->container))->send($command)
  > 80|                 ->through(array_merge(method_exists($command, 'middleware') ? $command->middleware() : [], $command->middleware ?? []))
    81|                 ->then(function ($command) use ($job) {
    82|                     return $this->dispatcher->dispatchNow(
    83|                         $command, $this->resolveHandler($job, $command)
    84|                     );

  Exception trace:

  1   Whoops\Run::handleError()
      /home/XXXXX.com/vendor/filp/whoops/src/Whoops/Run.php:486

  2   Whoops\Run::handleShutdown()
      [internal]:0

**Comment by assimon** [comment]
改了什么？动过什么？

**Comment by pinsecode** [comment]
> 
> 
> 改了什么？动过什么？

程序代碼沒改動過，全新安裝。

OS: Debian  9 (Py3.7.8)
PHP7.4.23
MySQL 5.7.34
Redis 6.2.5
MySQL 5.7.34
Nginx 1.18.0

**Comment by pinsecode** [comment]
重裝Redis 完美解決
