### ISSUE TITLE
其他输入框问题

### ISSUE THREAD

**Issue by sky-xk-nge** [assimon/dujiaoka#320]
在商品配置里面设置了其他输入框内容，但是在购买填写之后并不会在订单详细中显示！
![20210904091231](https://user-images.githubusercontent.com/68454687/132077657-6d198d7d-9615-4007-84bf-5f6ad039abe5.png)
![20210904091316](https://user-images.githubusercontent.com/68454687/132077660-2ec8655a-edcc-44e5-ba31-ad2002c632c7.png)
![20210904091359](https://user-images.githubusercontent.com/68454687/132077662-aba02ac8-5b91-4433-a5b3-1e99348b7aeb.png)

**Comment by assimon** [comment]
不要加[]
