### ISSUE TITLE
手动发货订单 卡密内容 在邮件里不能自动换行，乱成一锅粥

### ISSUE THREAD

**Issue by wangegou** [assimon/dujiaoka#322]
请问一下，手动发货订单 多个卡密放在一起发给客户，邮件里就会乱掉，不会自动换行，这个各位是怎么解决的？
![7D8A70710F1C8FB422D078AFB9FD3375](https://user-images.githubusercontent.com/50771267/132525171-c1b689a2-2560-4d73-8eaa-dcefde744b70.jpg)
![image](https://user-images.githubusercontent.com/50771267/132525440-a275580f-1b20-4f41-bcb3-c50aa3c935ef.png)

**Comment by wangegou** [comment]
请大佬给个修复建议

**Comment by assimon** [comment]
已解决，下个版本更新
