### ISSUE TITLE
更新最新commit文件后luna模板首页异常

### ISSUE THREAD

**Issue by alvincheang** [assimon/dujiaoka#323]
![Untitled](https://user-images.githubusercontent.com/79591502/133247550-83c01372-6504-4a40-a009-d52159e4b9c7.jpg)
根据最新commit替换文件更新后
luna模板无法正常显示商品了。
是哪里出问题了吗？

**Comment by assimon** [comment]
刷新浏览器缓存试试，无法得知具体错误

**Comment by alvincheang** [comment]
嗯 已试 还是一样。其他模板没问题 就luna这样

**Comment by assimon** [comment]
F12看看控制台有无报错，截图

**Comment by alvincheang** [comment]
![Untitled](https://user-images.githubusercontent.com/79591502/133251349-e12f3165-3396-41d5-a8f8-dce345aa60ea.jpg)
这个吗？可是那个layui我已经删除了 我看commit是删了layui不是吗？

**Comment by love2wind** [comment]
同样的问题，刷新缓存没有用。
![image](https://user-images.githubusercontent.com/11996852/136643145-adfc4ee6-5c3a-4944-8239-34117f7dd534.png)
