### ISSUE TITLE
請問如何加入“無限庫存”的自動發貨商品？

### ISSUE THREAD

**Issue by tsinit2001** [assimon/dujiaoka#325]
我準備發售可以不限使用次數的折扣代碼。不論有多少位顧客下單購買，都會得到同樣內容的折扣碼。
那麼除了給自動發貨商品填滿100行內容雷同的卡密，並且不斷隨着銷售進行補充之外，有沒其他途徑實現呢？

**Comment by assimon** [comment]
除了你所说的方式之外，暂时没有其他解决方案，可以自己对代码进行二次开发

**Comment by tsinit2001** [comment]
哦哦。知道了。謝謝大佬。
