### ISSUE TITLE
2.0.2 PP&Stripe 支付网关异常

### ISSUE THREAD

**Issue by BlueSkyXN** [assimon/dujiaoka#335]
在不变数据库的前提下（我的数据库），可以做到100%复现

主文件情况如下

1. 2代早期版本依次覆盖上来的文件包，用2.0.2文件包覆盖后可复现
2. 2.0.1包，删除旧文件，全新纯净安装的文件包，添加旧的env和数据库，正常
3. 在第二步基础上用2.0.2文件包覆盖后可复现
4. 在第三步基础上用，用2.0.1文件包覆盖后，恢复正常
5. 在第四步基础上用2.0.2文件包覆盖后可复现

[![photo_2021-11-01_20-00-33.jpg](https://s.pc.qq.com/tousu/img/20211101/6808820_1635769953.jpg)](https://s.pc.qq.com/tousu/img/20211101/6808820_1635769953.jpg)
[![photo_2021-11-01_20-00-32.jpg](https://s.pc.qq.com/tousu/img/20211101/1070637_1635769953.jpg)](https://s.pc.qq.com/tousu/img/20211101/1070637_1635769953.jpg)

在202中，CB正常，PP和Stripe异常
在201中，都正常（CB需要修改Route的pay.php）
出现异常只需要下单，本应该跳转到支付页面的那一步，则会如图所示报错

**Comment by BlueSkyXN** [comment]
修个图

[![photo_2021-11-01_20-00-32.jpg](https://imglf3.lf127.net/img/TXNkVjdFVk5ZSm1YOTloZnUyRUwxV3NPMzdmelZHZTFGTElISkdFeFBSUlNPSHNkZ1JQV1p3PT0.jpg)](https://imglf3.lf127.net/img/TXNkVjdFVk5ZSm1YOTloZnUyRUwxV3NPMzdmelZHZTFGTElISkdFeFBSUlNPSHNkZ1JQV1p3PT0.jpg)
[![photo_2021-11-01_20-00-33.jpg](https://imglf6.lf127.net/img/b2J0NWx0MmRFVEMyRm1qNGpLNExYZXVpd2thL3ZubmFOeHZxQ2hUS05jWUw0S3B5OUVsTE5nPT0.jpg)](https://imglf6.lf127.net/img/b2J0NWx0MmRFVEMyRm1qNGpLNExYZXVpd2thL3ZubmFOeHZxQ2hUS05jWUw0S3B5OUVsTE5nPT0.jpg)

**Comment by assimon** [comment]
没有这两个程序的依赖包，你直接加支付代码文件是没有用的！

**Comment by BlueSkyXN** [comment]
> 没有这两个程序的依赖包，你直接加支付代码文件是没有用的！

直接releases下载的发行包，文件都在

**Comment by assimon** [comment]
这个错误是包不存在，应该是依赖丢失了

**Comment by BlueSkyXN** [comment]
确实是有可能，需要我进一步研究

**Comment by thefreelight** [comment]
我也遇到同样的问题，请问老板解决了吗？我下载的是最新版2.0.2的发行包

**Comment by thefreelight** [comment]
解决了
composer update一下包就行

**Comment by BlueSkyXN** [comment]
> 解决了 composer update一下包就行

有具体操作方法吗，哪个包
