### ISSUE TITLE
安装完成后网站显示空白的问题解决

### ISSUE THREAD

**Issue by Smthie** [assimon/dujiaoka#338]
第一次装，严格按步骤来的，安装完成后，网站前台后台都是一片空白，且无任何报错，很迷惑。
重装系统重来还是不行，到处没找到解决方案，后来研究了几个小时发现是网站名称有空格的原因（个人习惯）。。。
解决方案：
1.去掉空格
2.加上双引号，如："独角 数卡"

**Comment by sucangit** [comment]
哈哈感谢 我昨晚也遇到了 问题已解决

**Comment by assimon** [comment]
开启debug其实可以看出报的错误是啥，不至于一片空白

**Comment by Smthie** [comment]
> 开启debug其实可以看出报的错误是啥，不至于一片空白

开了的，并没有报错。。

**Comment by assimon** [comment]
> > 开启debug其实可以看出报的错误是啥，不至于一片空白
> 
> 开了的，并没有报错。。

这就有点奇怪了  还没遇到过

**Comment by Smthie** [comment]
> > > 开启debug其实可以看出报的错误是啥，不至于一片空白
> > 
> > 
> > 开了的，并没有报错。。
> 
> 这就有点奇怪了 还没遇到过

经测试貌似这个问题100%复现，建议下个版本，配置文件变量加上引号。

**Comment by assimon** [comment]
下个版本会看看
