### ISSUE TITLE
后台配置系统配置失败

### ISSUE THREAD

**Issue by r1172464137** [assimon/dujiaoka#34]
![{EFA9C1A8-6501-4CD1-B3B2-96FF47E8B5A5} png](https://user-images.githubusercontent.com/29038520/80555705-a40be780-8a03-11ea-91e1-592bac78c03c.jpg)
在后台-<配置>-<系统配置>里不能进行修改，一旦进行修改就会出现上图的情况。
我的环境情况如下
![{03ACBBAC-5212-44DC-A764-E9BDB16E25E1} png](https://user-images.githubusercontent.com/29038520/80555823-fe0cad00-8a03-11ea-8338-29f41fbbe24f.jpg)
不知道是bug还是什么原因

**Comment by assimon** [comment]
> ![{EFA9C1A8-6501-4CD1-B3B2-96FF47E8B5A5} png](https://user-images.githubusercontent.com/29038520/80555705-a40be780-8a03-11ea-91e1-592bac78c03c.jpg)
> 在后台-<配置>-<系统配置>里不能进行修改，一旦进行修改就会出现上图的情况。
> 我的环境情况如下
> ![{03ACBBAC-5212-44DC-A764-E9BDB16E25E1} png](https://user-images.githubusercontent.com/29038520/80555823-fe0cad00-8a03-11ea-8338-29f41fbbe24f.jpg)
> 不知道是bug还是什么原因

检查一下php版本或者清理一下浏览器缓存，重启服务器试试，php版本最好7.2  按教程删除禁用函数
