### ISSUE TITLE
其他输入框配置问题

### ISSUE THREAD

**Issue by iawb-ray** [assimon/dujiaoka#345]
搭建方式：docker
最开始使用jiangjuhong/dujiaoka的镜像，为2.0.0版本，输入其他输入框配置后，商品页面未出现配置的输入框。
后来我手动拉取最新代码，构建镜像ray2333/dujiaoka，为2.0.2版本，问题依然存在。未在宝塔或LNMP环境下测试过。
以下是我的配置信息
![image](https://user-images.githubusercontent.com/49180084/146740952-48be35a1-bb36-4cfc-9181-47f895d60aa2.png)
以下是我的商品详情页面
![image](https://user-images.githubusercontent.com/49180084/146741026-b6df5686-14cc-40c5-bf73-ced361e1cb78.png)
是否与部署环境有关？

**Comment by assimon** [comment]
自动发货的商品就算你配置了其他输入框也不会显示，仔细看后台说明仅针对人工处理商品有效
