### ISSUE TITLE
支持邮件配置无加密方式

### ISSUE THREAD

**Issue by zpanel2000** [assimon/dujiaoka#349]
支持邮件配置无加密方式

**Comment by assimon** [comment]
![image](https://user-images.githubusercontent.com/35057561/147997496-3c1d5377-d371-49a3-be8e-c1af5a5f85bf.png)
这不是？

**Comment by 120420** [comment]
能否添加无ssl/tls的协议方式，邮局平台不支持ssl/tls的加密方式，非常感谢

**Comment by 120420** [comment]
好的，了解了
