### ISSUE TITLE
独角发卡同一服务器上搭建多个独角数卡出现的bug

### ISSUE THREAD

**Issue by Imcaochang** [assimon/dujiaoka#350]
我同一个服务器上搭建了超过三个独角发卡，发现了一个bug，会出现邮件无法送达，server酱无法推送，并且最重要的一点是
三个独角数卡的后台首页通知都是同一个，也就是说，我只要修改了其中的一个通知，那么其他的三个都会随之进行改变。
![image](https://user-images.githubusercontent.com/65030327/147430121-83f0d125-6c6b-4d95-bb4d-adf215a1c3dd.png)

目前测试发现应该是php的redis可能卡缓存了，邮件，server酱，推送都不会及时推送，三个独角发卡的邮件会互相发送

也就是说，我其中只有一个独角数卡配置了server酱，但其他另外两个的订单依旧会给我进行推送。

应该是redis或者是某一个键值的问题，建议测试看看，一台服务器上我搞了三个独角数卡，数据推送，邮件，通知，目前这三者消息是互相推送的...互通的

**Comment by CookieSir** [comment]
之前问过作者正好知道



在后网站1修改根目录的.env
 # redis配置 加一条  `REDIS_DB=0`

在后网站2修改根目录的.env
 # redis配置 加一条 `REDIS_DB=1`

在后网站2修改根目录的.env
 # redis配置 加一条 `REDIS_DB=2`

以此类推



在每个网站根目录的.env
`CACHE_DRIVER=redis`  修改为 `CACHE_DRIVER=file`
