### ISSUE TITLE
Vpay免签支付不会回调

### ISSUE THREAD

**Issue by suiyizjy** [assimon/dujiaoka#351]
大佬，你好，在使用V免签的时候接口都是正常的，也能够付款，但是付款之后 订单状态没有变

**Comment by alvincheang** [comment]
应该就是自己监控软件的问题。我用就好好的 :D

**Comment by suiyizjy** [comment]
我监控软件也一样是配置好的，都能够正常运行，也能够对接起来。但是不管怎么设置 都是无法正常回调，支付完成之后 直接不跳转了。

**Comment by alvincheang** [comment]
监控正常运行并不是重点
重点是你的监控软件有没监控到款项，没监控到的话当然就不会回调了
检查你的监控软件
不跳转都是监控软件没监控的你的款项

**Comment by suiyizjy** [comment]
好的 明白了
我找了一圈监控软件都不行
你有推荐的吗 ？谢谢

**Comment by alvincheang** [comment]
我用的pc监控 https://pmhapp.com/wd_vpay/
手机的我也不行 所以已放弃

**Comment by suiyizjy** [comment]
好的，谢谢，这个版本的我用了也不行 ，可能是我电脑系统软件的问题吧，我再测试看看
