### ISSUE TITLE
paypal  stripe  问题

### ISSUE THREAD

**Issue by MOSSSN** [assimon/dujiaoka#356]
1.82版本的paypal可以正常使用
 2.0以上paypal都是401错误.  
error
GOT HTTP RESPONSE CODE 401 WHEN ACCESSING HTTPS://API.PAYPAL.COM/V1/OAUTH2/TOKEN.

把2.0以上版本中 那个PaypalPayController.php 替换成1.82那个PaypalPayController.php后

显示Class 'App\Http\Controllers\Pay\PayController' not found

这个大佬们遇到没有.

想同时用1.82版本的paypal  和2.01的 stripe .还有2.02的coinbase TG推送

请大佬们说一下怎么整合在一起

**Comment by assimon** [comment]
需要自己开发，1.8和2.0变动太多了
