### ISSUE TITLE
安装的时候出现The POST method is not supported for this route. Supported methods: GET, HEAD

### ISSUE THREAD

**Issue by YinBuLiao** [assimon/dujiaoka#358]
![image](https://user-images.githubusercontent.com/35324248/151951539-2db77b50-0750-4527-a5f1-26b834759c5a.png)

**Comment by Ackites** [comment]
同问

**Comment by Ackites** [comment]
已经解决问题，可以连接服务器后，进入根目录，执行：php artisan route:cache，就可以解决问题了

**Comment by SurpriseLon** [comment]
LogicException  : Unable to prepare route [api/user] for serialization. Uses Closure.
  at /www/wwwroot/xxx/vendor/laravel/framework/src/Illuminate/Routing/Route.php:917
    913|      */
    914|     public function prepareForSerialization()
    915|     {
    916|         if ($this->action['uses'] instanceof Closure) {
  > 917|             throw new LogicException("Unable to prepare route [{$this->uri}] for serialization. Uses Closure.");
    918|         }
    919| 
    920|         $this->compileRoute();
    921|
