### ISSUE TITLE
无法发送邮箱

### ISSUE THREAD

**Issue by huan620** [assimon/dujiaoka#360]
环境 Debian 11 PHP-7.4,Nginx-1.21.4,MySQL 10.1.47-MariaDB,Redis 6.2.6,宝塔应用管理器1.5
1. 守护进程开着(使用宝塔应用管理器)
2. 根证书换了
3. Telegram bot推送可以用
4. 在其他平台邮箱可用(同机器)
5. 文档中所有提到插件已安装
6. 尝试过重装系统(服务器搬迁)
7. 尝试过自建邮局，Outlook，Gmail
8. 尝试过覆盖网站源码
9. 最新版本
10. tcpping 25，587端口都ping得通，两个端口都没有被占用
![IMG_20220209_145356_484](https://user-images.githubusercontent.com/67591552/153137537-e842cf8d-30ae-40fb-ba84-b193d62b1bfd.jpg)
![IMG_20220209_145354_640](https://user-images.githubusercontent.com/67591552/153137544-e43f0211-315b-4c2b-95b5-e6836ecc4aad.jpg)
![IMG_20220209_145353_798](https://user-images.githubusercontent.com/67591552/153137555-f3971b80-8afe-4be3-a5b1-643e6870bdc1.jpg)

**Comment by xiaorui16888** [comment]
我也一样，求解答，谢谢！

**Comment by assimon** [comment]
尝试更换端口为465或者协议改为ssl
