### ISSUE TITLE
luna生成的商品链接无法生成站点地图

### ISSUE THREAD

**Issue by zhongshuiyuan** [assimon/dujiaoka#364]
luna生成的商品链接无法自动加上域名或者ip，导致不能生成站点地图

此图无法生成站点地图
![image](https://user-images.githubusercontent.com/8955999/158528059-ba764e15-2493-4bf0-89f6-b91ab5edac91.png)

此图可以
![image](https://user-images.githubusercontent.com/8955999/158528210-2f408a41-2591-4368-bba3-680848b2325c.png)

**Comment by assimon** [comment]
luna的作者暂停更新了
