### ISSUE TITLE
关于批发价的bug

### ISSUE THREAD

**Issue by iLay1678** [assimon/dujiaoka#41]
当商品存在2个或两个以上批发价时，foreach到第二个时，购买数量达不到第二个批发数量，就会出现批发优惠无效。我的pr中已修复该问题。

https://github.com/iLay1678/dujiaoka/commit/0a90c6b7e3c8ccfa78e21c03068bb5a7c5ab4bb4

**Comment by assimon** [comment]
> 在2个或两个以

我看了一下这个pr，我暂时没有发现优惠无效的问题，但是我看了一下你的pr，删除了我一段代码，会导致金额错误问题。之前我遇到过这个bug
