### ISSUE TITLE
这系统支持英语吗？

### ISSUE THREAD

**Issue by zhujitop** [assimon/dujiaoka#48]
因为网站外国人比较多，想找个有英语界面支持的。

不知道系统支持不？或者有没有类似Wordpress语言包功能，自己翻译语言文件也行。

**Comment by assimon** [comment]
> 因为网站外国人比较多，想找个有英语界面支持的。
> 
> 不知道系统支持不？或者有没有类似Wordpress语言包功能，自己翻译语言文件也行。

目前不支持
