### ISSUE TITLE
宝塔面板搭建独角数卡网站，导入spl文件后，去访问我的域名，网站不能正常访问。

### ISSUE THREAD

**Issue by GitHub-ZhangHao** [assimon/dujiaoka#49]
宝塔面板搭建独角数卡网站，导入spl文件后，去访问我的域名，网站不能正常访问。
它显示：404 Site 域名 is not served on this interface
请问这是怎么回事？我要如何解决？（phpmyadmin是4.4版本而非4.9版本，另外那个build压缩包解压后是两个文件夹，而非视频中的一个，除此之外其他的操作完全跟教程视频中的一样）
![QQ图片20200630082146](https://user-images.githubusercontent.com/64506378/86068830-e0fb6580-baaa-11ea-94b7-5800d89f9b69.jpg)

**Comment by assimon** [comment]
> 请问这是怎么回事？我要如何解决？（phpmyadmin是4.4版本而非4.9版本，另外那个build压缩包解压后是两个文件夹，而非视频中的一个，除此之外其他的操作完全跟教程视频中的一样）

伪静态是否未设置？运行目录是public吗

**Comment by GitHub-ZhangHao** [comment]
> > 请问这是怎么回事？我要如何解决？（phpmyadmin是4.4版本而不是4.9版本，另外那个build压缩包解压后是两个文件夹，而不是视频中的一个，其他其他的操作完全跟教程视频中的一样）
> 
> 伪静态是否未设置？运行目录是public吗

感谢回复，已经好了，应该是因为我的nginx没有运行。我还有俩个问题想问你：买家购买的卡密购买后是在网页显示还是会发送到买家在购买时留的邮箱里？我试了一下，它是网页显示，不知道是不是我邮箱没有设置好。邮件服务配置中改端口465或22，需不需要在vps终端开放这两个端口？

**Comment by assimon** [comment]
> > > 请问这是怎么回事？我要如何解决？（phpmyadmin是4.4版本而不是4.9版本，另外那个build压缩包解压后是两个文件夹，而不是视频中的一个，其他其他的操作完全跟教程视频中的一样）
> > 
> > 
> > 伪静态是否未设置？运行目录是public吗
> 
> 感谢回复，已经好了，应该是因为我的nginx没有运行。我还有俩个问题想问你：买家购买的卡密购买后是在网页显示还是会发送到买家在购买时留的邮箱里？我试了一下，它是网页显示，不知道是不是我邮箱没有设置好。邮件服务配置中改端口465或22，需不需要在vps终端开放这两个端口？

改了邮件相关的东西需要重启supervisor进程，建议端口挨个试试。我也不知道你用的什么邮箱
