### ISSUE TITLE
添加商品出错

### ISSUE THREAD

**Issue by 0i** [assimon/dujiaoka#50]
添加商品页面，js报错 An invalid form control with name='' is not focusable. 无法保存或者编辑商品

**Comment by assimon** [comment]
> An invalid form control with name='' is not focusable

是不是开https了，开了的话.env里面也需要配置

**Comment by 0i** [comment]
没有开https，用最新版的 Chrome 和 Safari 都测试过，不行。

**Comment by 0i** [comment]
每次编辑商品都必须要重新上传一次图片才行 @assimon

**Comment by 0i** [comment]
这个bug 感觉很影响用户体验啊

**Comment by assimon** [comment]
> 这个bug 感觉很影响用户体验啊

使用1.6版本把，你描述的这个bug是最早期才会有的，早就修复了。最新版我没发现这个问题

**Comment by 0i** [comment]
就是使用的1.6的版本

**Comment by 0i** [comment]
Env   local      Version   1.7.14

**Comment by 0i** [comment]
git clone 安装的

**Comment by assimon** [comment]
我这边测试没有发现这个问题，其他用户也没有反馈，建议强制刷新一下浏览器缓存

**Comment by 0i** [comment]
强制刷新后仍然有这个错误

**Comment by assimon** [comment]
是不是换过后台主题，.env里面，这里可能有个bug，建议使用原版的主题

**Comment by assimon** [comment]
> 强制刷新后仍然有这个错误

这个问题已经得到修复了，图片裁剪扩展包导致的，安装最新1.6发行包，刷新一下浏览器缓存即可

**Comment by 0i** [comment]
👌
