### ISSUE TITLE
可以提交宝塔一键部署么？

### ISSUE THREAD

**Issue by coderykw** [assimon/dujiaoka#51]
可以提交宝塔一键部署么？ 大佬

**Comment by assimon** [comment]
怎么提交，宝塔我不会发布

**Comment by iLay1678** [comment]
> 怎么提交，宝塔我不会发布

https://www.bt.cn/bbs/thread-33063-1-1.html

**Comment by coderykw** [comment]
或者简化安装步骤也行~ 我之前装过独角兽成功了 再装1.6就&nbsp; astian命令 notfound




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "我若为王"<notifications@github.com&gt;; 
发送时间: 2020年7月7日(星期二) 下午5:03
收件人: "assimon/dujiaoka"<dujiaoka@noreply.github.com&gt;; 
抄送: "羊王大大"<526121793@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [assimon/dujiaoka] 可以提交宝塔一键部署么？ (#51)





  
怎么提交，宝塔我不会发布
  
https://www.bt.cn/bbs/thread-33063-1-1.html
 
&mdash;

**Comment by assimon** [comment]
其实你过一遍视频教程就会发现安装过程并不困难，只要环境安装好了就很稳定，laravel框架是这样的，一些特定的配置需要手动改
