### ISSUE TITLE
添加卡密有错误啊

### ISSUE THREAD

**Issue by ofdjonf** [assimon/dujiaoka#52]
导入卡密点击提交出现：Whoops, looks like something went wrong.怎么回事啊？真难搞

**Comment by assimon** [comment]
> 导入卡密点击提交出现：Whoops, looks like something went wrong.怎么回事啊？真难搞

如果强制https访问，那么.env里面配置需要开启https，具体看.env里面配置说明

**Comment by ofdjonf** [comment]
大佬，能给我说下，我都升级了最新版本了，为什么添加商品还是提示需要添加图片。这个怎么搞的。

ashang <notifications@github.com> 于 2020年7月8日周三 21:34写道：
