### ISSUE TITLE
安装时导入SQL文件报错

### ISSUE THREAD

**Issue by isyume** [assimon/dujiaoka#53]
在执行artisan这一步报错：

PHP Parse error:  syntax error, unexpected '=' in /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Support/Arr.php on line 416

Parse error: syntax error, unexpected '=' in /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Support/Arr.php on line 416

版本信息： PHP 7.1
最新版独角兽源码
四个要求的函数已从禁用删除

**Comment by assimon** [comment]
> 在执行artisan这一步报错：
> 
> PHP Parse error: syntax error, unexpected '=' in /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Support/Arr.php on line 416
> 
> Parse error: syntax error, unexpected '=' in /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Support/Arr.php on line 416
> 
> 版本信息： PHP 7.1
> 最新版独角兽源码
> 四个要求的函数已从禁用删除

终端执行php -v命令，应该是你终端内置的php版本对应不上宝塔版本

**Comment by assimon** [comment]
看文档宝塔安装篇，有详细介绍

**Comment by assimon** [comment]
视频教程过一遍
