### ISSUE TITLE
请教卡密怎么重复使用呢？码支付微信啥时候安排一下

### ISSUE THREAD

**Issue by coderykw** [assimon/dujiaoka#54]
~打算慢慢从zf迁移到独角兽~~

**Comment by assimon** [comment]
> ~打算慢慢从zf迁移到独角兽~~

码支付微信不是有吗？重复导入卡密就行了，不要勾选去重

**Comment by coderykw** [comment]
我显示码支付 待开放



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ashang <notifications@github.com&gt;
发送时间: 2020年7月10日 10:26
收件人: assimon/dujiaoka <dujiaoka@noreply.github.com&gt;
抄送: 羊王 <526121793@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[assimon/dujiaoka] 请教卡密怎么重复使用呢？码支付微信啥时候安排一下 (#54)





  
~打算慢慢从zf迁移到独角兽~~
  
码支付微信不是有吗？重复导入卡密就行了，不要勾选去重

**Comment by assimon** [comment]
那是我测试忘了删，实际是可以用的
