### ISSUE TITLE
支付成功后没有弹出卡密

### ISSUE THREAD

**Issue by BigBigfeifan** [assimon/dujiaoka#55]
我想问下为什么支付成功后无法弹出卡密的，查订单也没有任何记录？

**Comment by assimon** [comment]
> 我想问下为什么支付成功后无法弹出卡密的，查订单也没有任何记录？

什么支付？

**Comment by BigBigfeifan** [comment]
支付宝pc，能支付成功，但是支付后跳转回来发现并没有添加到订单

**Comment by assimon** [comment]
支付宝公钥配置错了，建议网上找找教程

**Comment by BigBigfeifan** [comment]
那个微信扫码的支付方式是native支付么？

**Comment by assimon** [comment]
是的
