### ISSUE TITLE
关于运行环境的询问

### ISSUE THREAD

**Issue by QiankunAss** [assimon/dujiaoka#56]
作者大大，请问只能在linux 系统运行么，没有适配于windows的源码么。
在安装环境我也看了，emmm，说实话不舍得windows 做成 linux，因为要挂很多东西，包括校验程序。

**Comment by QiankunAss** [comment]
啊 这 ，今天上午我测试了一下，卡在SQL了，我的宝塔也没有lv5的伪静态，但是我手动输入了一下你截图的的代码。

由于没有导入数据库，现在访问是500

我想手动导入，但是 数据库在哪!??!

大佬 做个 windows的教程把，秋梨膏

**Comment by QiankunAss** [comment]
环境是windows + PHP7.1  和 IIS

**Comment by jiaozibufu** [comment]
这玩意只支持nginx貌似,另外windows做网站的话无论是安全还是性能都比不过linux,如果是要搞好发卡网不建议windows呢

**Comment by QiankunAss** [comment]
好的吧，难定。

**Comment by assimon** [comment]
windows上配置极其糟糕，因为不支持一些linux的特性。为了闭坑建议直接linux，windows上的问题折腾不完的

**Comment by QiankunAss** [comment]
> Windows上配置极为恶劣，因为不支持一些Linux的特性。为了闭坑建议直接Linux，Windows上的问题折腾不完的

哎，但是我有许多 软件 需要在Windows的环境下 运行挂着。

我再去找一个Linux的服务器吧，难定。
