### ISSUE TITLE
关于Supervisor配置

### ISSUE THREAD

**Issue by jiaozibufu** [assimon/dujiaoka#57]
作者写的教程无法适配新版本宝塔,请问这个该怎么写啊
https://s1.ax1x.com/2020/07/17/UsAdVf.png
这是新版本宝塔的配置选项

**Comment by assimon** [comment]
> 作者写的教程无法适配新版本宝塔,请问这个该怎么写啊
> https://s1.ax1x.com/2020/07/17/UsAdVf.png
> 这是新版本宝塔的配置选项

可以看看宝塔安装篇的视频教程，有讲
