### ISSUE TITLE
哪位大神救救我,,邮箱死活配置不上,,各种邮箱各种端口都尝试了

### ISSUE THREAD

**Issue by dylanbai8** [assimon/dujiaoka#61]
宝塔环境,,阿里云香港服务器,,尝试了163\阿里云\gmail 邮箱..
难道是端口被屏蔽了?么
求教其它的订单通知方式,,主要是通知我自己知道有人下单了..

**Comment by dylanbai8** [comment]
是需要安装 imap扩展 吗?,

**Comment by assimon** [comment]
.env文件里面的MAIL_ENCRYPTION改成ssl或者tls试试，邮件配置改了任何东西都需要重启supervisor进程才会生效，建议挨个试试

**Comment by dylanbai8** [comment]
感谢感谢，已搞定。
加ssl就行了，我也是蒙了。。。。

贴一下aliyun邮箱的配置，方便后来人。

# 邮件服务配置
MAIL_DRIVER=smtp
MAIL_HOST=smtp.aliyun.com
MAIL_PORT=465
MAIL_USERNAME=xxxxxxx@aliyun.com
MAIL_PASSWORD=qq130130
MAIL_FROM_ADDRESS=xxxxxxx@aliyun.com
MAIL_FROM_NAME=独角兽商店
MAIL_ENCRYPTION=ssl
