### ISSUE TITLE
反馈一个bug,,支付宝当面付款完成后,弹出确定按钮

### ISSUE THREAD

**Issue by dylanbai8** [assimon/dujiaoka#62]
反馈一个bug,,支付宝当面付款完成后,弹出确定按钮,,
如果点确定可以正常发卡,,如果点x关闭弹窗则不能跳转到发卡页面..

**Comment by dylanbai8** [comment]
有些客户就是点x,,,不点确定,,也不知道他们怎么想的....

**Comment by assimon** [comment]
当面付支付完成后会自动跳转，不需要手动跳

**Comment by dylanbai8** [comment]
![QQ截图20200723122155.png](https://i.loli.net/2020/07/23/vMkH3QE8ZOSLemK.png)

不会自动跳转呀，老铁。会永远停留在这个页面。

如果点x关闭弹窗，就会永远停留在扫码页面。

（ ps. 截图里“请点确定”是我自己添加的）

**Comment by assimon** [comment]
下个版本修复

**Comment by dylanbai8** [comment]
非常感谢！
