### ISSUE TITLE
【建议】关于购买时输入验证码错误

### ISSUE THREAD

**Issue by gimgoo** [assimon/dujiaoka#63]
购买商品时输入验证码错误会跳转到一个提示验证码错误的页面，但是当返回的时候，刚才填写的邮箱，跟查询密码，优惠码都要重新填，用户体验感很不好，建议保留用户所输入的。

**Comment by dylanbai8** [comment]
而且验证码还不会自动刷新,还是之前的验证码

**Comment by gimgoo** [comment]
这建议这么重要，你非但不屑，还关掉，反而在那些不重要的细枝末节上花时间，你怎么想的？

**Comment by assimon** [comment]
第一，你是从何得知我不屑？每个版本的优化计划都在安排中，此项建议只不过是下次版本的计划，此功能也不是影响正常使用的严重缺陷
第二，什么叫不重要的细枝末节？很多更新提交都是第三方用户提交上来的pr更新，不求感谢别人也别用这种语气？
第三，为什么要把每项建议意见都当成开发者的义务？好像我没有从独角数卡上收取任何费用把？
第四，如果你觉得这个功能实在很重要，代码都是开源的你为什么不舍得花一点时间自己改一下？非要用这种语气来要求作者更新？
