### ISSUE TITLE
payjs支付成功后，停留在payjs扫描界面，不发卡

### ISSUE THREAD

**Issue by dylanbai8** [assimon/dujiaoka#64]
payjs支付成功后，停留在payjs扫描界面，不发卡
如果需要，可以协助测试
感谢老铁开发

**Comment by dylanbai8** [comment]
![QQ截图20200723122750.png](https://i.loli.net/2020/07/23/DCZ9O2JIaEsy7tG.png)

如图，payjs支付下单会跳转到这个页面，扫码支付完成后没有任何反应 永久停留在这个页面。

**Comment by assimon** [comment]
下个版本修复

**Comment by dylanbai8** [comment]
辛苦了，老铁。期待

**Comment by BeyondIM** [comment]
1.8.2 版还是存在这个问题
