### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by ddgth** [assimon/dujiaoka#70]
PHP Warning:  require(/var/www/shop/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/shop/artisan on line 18
PHP Fatal error:  require(): Failed opening required '/var/www/shop/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/shop/artisan on line 18

**Comment by iLay1678** [comment]
要么下载release里的全量包后部署，要么composer insatall安装依赖包，直接下载的源码不包含依赖包

**Comment by ddgth** [comment]
> 要么下载release里的全量包后部署，要么composer insatall安装依赖包，直接下载的源码不包含依赖包

composer install 执行的时候出现这个错误  我确定远程数据库配置的是正确的
Illuminate\Database\QueryException  : SQLSTATE[HY000] [1045] Access denied for user 'root'@'xx.xx.xx.xx' (using password: YES) (SQL: select * from information_schema.tables where table_schema = shop and table_name = admin_config and table_type = 'BASE TABLE')
