### ISSUE TITLE
请问首页可以显示销量吗

### ISSUE THREAD

**Issue by zipcheung** [assimon/dujiaoka#71]
rt

**Comment by assimon** [comment]
有保留字段，但是我这边没有进行显示，不想在首页展示太多字段显得混乱，而且这个也不是什么强性需求

**Comment by zipcheung** [comment]
请问怎么在何处设置可以显示呢

**Comment by assimon** [comment]
这个需要你有一点点html和php的基础啦

**Comment by zipcheung** [comment]
请问具体要修改哪里呢，我找了一下没有找到，谢谢

**Comment by assimon** [comment]
resources/views/layui/static_pages/home.blade.php
