### ISSUE TITLE
如何关闭下单以及后台登录的验证码

### ISSUE THREAD

**Issue by loveqianool** [assimon/dujiaoka#77]
你好，请问有选项，或者修改任何配置可以关掉后台登录以及下单页面的验证码吗？
还有下单页面的优惠码，可以配置不显示吗？老是有人问优惠，但是我的商品都是没有优惠的。

**Comment by cyz0105** [comment]
当然可以。在/manage页的左边，找 配置---系统配置---下单验证码---关闭。商品优惠码关闭，需要在商品管理---商品列表---想要关闭优惠券的商品---优惠券入口---关闭。
