### ISSUE TITLE
宝塔进程守护没有启动参数了

### ISSUE THREAD

**Issue by wangxds** [assimon/dujiaoka#79]
![image](https://user-images.githubusercontent.com/25134062/90750546-8abade00-e307-11ea-9de0-0f1565aafe55.png)
宝塔进程守护没有启动参数了，该如何配置呢

**Comment by wangxds** [comment]
宝塔版本7.4.2

**Comment by assimon** [comment]
数据库连接错误，检查一下.env里面的数据库配置

**Comment by wangxds** [comment]
> 数据库连接错误，检查一下.env里面的数据库配置

后台数据添加啥的都是一切正常呀，我检查了也没看到有问题

**Comment by assimon** [comment]
贴一下数据库配置，马赛克掉关键信息。然后数据库表导入没有？

**Comment by wangxds** [comment]
> 贴一下数据库配置，马赛克掉关键信息。然后数据库表导入没有？

![image](https://user-images.githubusercontent.com/25134062/91005544-bd1b5280-e609-11ea-992c-661e6b1d3b11.png)
shujuku数据库通过 artisan 命令导入了的 并且数据表里面有内容

**Comment by assimon** [comment]
这个报错是网页上的还是supervisor得？

**Comment by wangxds** [comment]
> supervisor

supervisor的报错

**Comment by assimon** [comment]
这个错误就是数据库连接不上，重启下supervisor试试呢

**Comment by assimon** [comment]
admin_config这个表在不在数据库？

**Comment by wangxds** [comment]
> admin_config这个表在不在数据库？
![image](https://user-images.githubusercontent.com/25134062/91005830-724e0a80-e60a-11ea-8109-e7aa0c8c6cd7.png)
你看下这个

**Comment by assimon** [comment]
127.0.0.1改成localhost呢？再仔细核对一下数据库信息

**Comment by wangxds** [comment]
> 127.0.0.1改成localhost呢？再仔细核对一下数据库信息

按理来说后台能添加数据 配置就不应该有问题呀，有没有办法让supervisor的日志马上出来

**Comment by wangxds** [comment]
> 127.0.0.1改成localhost呢？再仔细核对一下数据库信息

/www/server/php/72/bin/php /www/wwwroot/xxxxxx/artisan queue:work   这是我supervisor启动命令

**Comment by assimon** [comment]
............-_-||，后台都能访问了证明就是正确的，这个错误日志可能是之前的。你测试一下看看能不能购买商品后发货？或者提交订单过一会库存会不会恢复

**Comment by wangxds** [comment]
> ............-_-||，后台都能访问了证明就是正确的，这个错误日志可能是之前的。你测试一下看看能不能购买商品后发货？或者提交订单过一会库存会不会恢复

好的，我再开一个问题咨询一下码支付

**Comment by wangxds** [comment]
> ............-_-||，后台都能访问了证明就是正确的，这个错误日志可能是之前的。你测试一下看看能不能购买商品后发货？或者提交订单过一会库存会不会恢复

后台的QQ群链接好像失效了，不会弹出QQ加群，方便给一下群号吗

**Comment by assimon** [comment]
568679748

**Comment by wangxds** [comment]
> 568679748

OK谢谢 进去了
