### ISSUE TITLE
后台修改头像后，无法加载

### ISSUE THREAD

**Issue by zuoshouzz** [assimon/dujiaoka#81]

**Comment by assimon** [comment]
开debug，给出具体错误，就说个无法加载靠猜么==

**Comment by zuoshouzz** [comment]
> 开debug，给出具体错误，就说个无法加载靠猜么==

上传路径，/uploads/images/5573fe5121a7bb601df4e47e1f70e1d2.jpg 
后台无法加载，怎么修

**Comment by assimon** [comment]
.env里面把APP_URI改成你的网站

**Comment by zuoshouzz** [comment]
> APP_URI

ths
