### ISSUE TITLE
建议对接Server酱

### ISSUE THREAD

**Issue by wangxds** [assimon/dujiaoka#82]
Server酱，有免费版和刚出的测试版号（捐赠版），为了稳定我提供一下测试版号官网 [Server酱(测试版号-捐赠版)](https://sct.ftqq.com/)

对接后方便接收新订单、库存等信息的微信推送，邮件不是随时都能看到，微信就不一样了，哈哈，望采纳

**Comment by assimon** [comment]
已归入下个版本迭代计划

**Comment by wangxds** [comment]
> 已归入下个版本迭代计划

留下没有技术的眼泪，辛苦了
