### ISSUE TITLE
supervisor占满了cpu怎么办？

### ISSUE THREAD

**Issue by ddgth** [assimon/dujiaoka#85]
作者你好 
我运行supervisor后发现php进程占满了CPU 请问有解决的办法了
24049 www-data  20   0  108312  34772  21216 R  15.6   3.4   0:00.15 /usr/bin/php /var/www/shop/artisan queue:work --tries=3                    
24039 www-data  20   0  108340  34768  21072 R  15.6   3.4   0:00.21 /usr/bin/php /var/www/shop/artisan queue:work --tries=3                    
24048 www-data  20   0  108276  34752  21196 R  15.6   3.4   0:00.17 /usr/bin/php /var/www/shop/artisan queue:work --tries=3                    
24047 www-data  20   0  108288  34460  20904 R  13.3   3.4   0:00.17 /usr/bin/php /var/www/shop/artisan queue:work --tries=3                    
24050 www-data  20   0  108312  32540  21040 R  15.6   3.2   0:00.14 /usr/bin/php /var/www/shop/artisan queue:work --tries=3                    
24054 www-data  20   0  106228  32344  20840 R  15.6   3.2   0:00.14 /usr/bin/php /var/www/shop/artisan queue:work --tries=3

**Comment by assimon** [comment]
看下日志有报错么

**Comment by ddgth** [comment]
> 看下日志有报错么

日志没有报错 我进程kill掉 然后重启系统 暂时搞定了

**Comment by assimon** [comment]
行，那你再观察观察
