### ISSUE TITLE
不支持mysql8.0吗？

### ISSUE THREAD

**Issue by zhujitop** [assimon/dujiaoka#90]
安装的时候一直提示数据库错误

php7.4.8，mysql8.0
配置文件.env核对了好几次，数据库账户密码都正常，也给了权限。

`Illuminate\Database\QueryException  : SQLSTATE[HY000] [1045] Access denied for user 'root'@'127.0.0.1' (using password: YES) (SQL: select * from information_schema.tables where table_schema = soft and table_name = admin_config and table_type = 'BASE TABLE')`

同服务器下还有安装了隔壁card-system的系统，很久了一直正常使用，那应该不是环境问题吧？
不知道是啥引起的错误？

**Comment by assimon** [comment]
我没用那么高版本的mysql，建议用5.7

**Comment by YulinChan** [comment]
mariadb最新版岂不是没戏？
