### ISSUE TITLE
nginx报错

### ISSUE THREAD

**Issue by 1515806183** [assimon/dujiaoka#91]
"Unable to open primary script: /root/dujiaoka_build/public/index.php (No such file or directory)" 

但是又这个目录，配置如下
  server {
        listen       80 default_server;  
        listen       [::]:80 default_server;
        server_name  _;
        root         /www/wwwroot/dujiaoka_build/public;

        index index.html index.htm index.php;
        location / {
        try_files $uri $uri/ /index.php$is_args$query_string;
        }
        # Load configuration files for the default server block.
        location ~ \.php$
        {
        fastcgi_pass   127.0.0.1:9000;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME /root/dujiaoka_build/public$fastcgi_script_name;
        include        fastcgi_params;
         }
        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }

**Comment by assimon** [comment]
配置没对，再好好用搜索引擎琢磨下，或者直接看宝塔教程
