### ISSUE TITLE
建议增加v免签

### ISSUE THREAD

**Issue by jiuyueidc** [assimon/dujiaoka#92]
收款即时到账，无需进入第三方账户，收款更安全
提供示例代码简单接入
超简单Api使用，提供统一Api实现收款回调
免费、开源，无后门风险
支持监听店员收款信息，可使用支付宝微信小号/模拟器挂机，方便IOS用户
免root，免xp框架，不修改支付宝/微信客户端，防封更安全
[https://github.com/szvone/vmqphp](https://github.com/szvone/vmqphp)

**Comment by assimon** [comment]
已列入计划，静候更新

**Comment by iLay1678** [comment]
> 已列入计划，静候更新

V免签我不是加上了吗。。。
