### ISSUE TITLE
SMTP不能发送邮件

### ISSUE THREAD

**Issue by ojbk8** [assimon/dujiaoka#93]
我是在LINUX纯净系统手动搭建的环境，没用面板、一键lnmp包等。在相同的站点配置环境下，SMTP参数在wordpress的插件里面测试能正常发送邮件.gmail与Yandex的SMTP参数设置.env我多次检查确认了正确无误，SMTP邮箱没有发送记录，下单邮箱与接收未处理订单的邮箱始终收不到任何订单提示邮件，尝试清空mysql更换了tls,ssl或587，465重新导入SQL还是不行，自动发货、代充均可以正常下单购买

**Comment by assimon** [comment]
更改邮件配置后要重启supervisor才会生效

**Comment by pwwq** [comment]
搞定了，  请问caddy2的伪静态规则怎么写。

**Comment by ojbk8** [comment]
搞定  之前Supervisor没装，原来是要么使用Supervisor管理 Laravel 队列进程，现在Supervisor配置好了，不装的话必须要么在站点根目录下面执行`php artisan queue:work`

**Comment by assimon** [comment]
执行php artisan queue:work你退出终端后就会自动取消执行，建议还是用Supervisor监听。
Caddy2我没用过帮不上你😁

**Comment by 1515806183** [comment]
配置了Supervisor，端口也开发，为啥还是不能接受短信，手动php artisan queue:work，显示失败
