### ISSUE TITLE
建议payjs增加收银台模式，满足手机支付能力

### ISSUE THREAD

**Issue by jiuyueidc** [assimon/dujiaoka#94]
现在的payjs支付，只能电脑端手机通过摄像头扫码支付，不能截图通过相册识别。
*希望增加收银台模式，满足手机支付能力*
[payjs收银台模式](https://help.payjs.cn/api/cashier.html)

**Comment by qihaimi** [comment]
臣附议！

**Comment by wfion** [comment]
附议！
