### ISSUE TITLE
新款supervisor怎么设置。

### ISSUE THREAD

**Issue by wangwangyh** [assimon/dujiaoka#96]
没有启动参数那一栏了。缺失也可以吗

**Comment by wangwangyh** [comment]
我反正supervisor启动失败了。。前一步输入网址可以显示了

**Comment by wangwangyh** [comment]
Parse error: syntax error, unexpected '?' in /www/wwwroot/bobofaka.top/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 252

**Comment by assimon** [comment]
视频教程里面有讲哦

**Comment by wangwangyh** [comment]
> 视频教程里面有讲哦

谢谢大佬，建议大家结合视频享用，效果更佳
