### ISSUE TITLE
vpay支付“通知失败”导致重复发卡，一个订单对应2个卡密

### ISSUE THREAD

**Issue by dylanbai8** [assimon/dujiaoka#97]
vpay支付“通知失败”导致重复发卡，一个订单对应2个卡密。剩余库存数混乱。

![image](https://user-images.githubusercontent.com/26950227/94879758-bba83a00-0493-11eb-9cab-a255a4ef8148.png)

![image](https://user-images.githubusercontent.com/26950227/94879776-cebb0a00-0493-11eb-914f-7ea442ac2a38.png)

![image](https://user-images.githubusercontent.com/26950227/94879599-45a3d300-0493-11eb-88e1-1b613981f571.png)

![image](https://user-images.githubusercontent.com/26950227/94879608-4f2d3b00-0493-11eb-9a0a-3804c8050974.png)

**Comment by assimon** [comment]
@iLay1678

**Comment by iLay1678** [comment]
> @iLay1678

理论上不会这样的，回调只会处理一次，处理完一次不就从redis删除订单了吗，目前只发现他这里出现问题，不排除其他原因
