### ISSUE TITLE
保存配置提示The GET method is not supported for this route. Supported methods: POST.

### ISSUE THREAD

**Issue by cashkiller** [assimon/dujiaoka#98]
保存配置提示The GET method is not supported for this route. Supported methods: POST.
[![postcee4eb96f926b5c4.png](https://imgurl.me/images/2020/10/06/postcee4eb96f926b5c4.png)](https://imgurl.me/image/dkayT)

**Comment by assimon** [comment]
是不是开启了强制HTTPS，.env里面也开启一下

**Comment by Amiking** [comment]
> 是不是开启了强制HTTPS，.env里面也开启一下

大佬NP，感谢

**Comment by cashkiller** [comment]
> 是不是开启了强制HTTPS，.env里面也开启一下

果然解决了，NB~，谢谢
接下来准备试试加自己二开的免签接口耍一下~
