### ISSUE TITLE
访问问题

### ISSUE THREAD

**Issue by wangwangyh** [assimon/dujiaoka#99]
我本身是香港服务器，然后用同一个域名，其他网站可以访问，这个独角兽发卡移动网络访问效果很差。有没有加速的办法。本人小白。谢谢大佬了

**Comment by wangwangyh** [comment]
是不是跟本身的设置或者代码也有关系？其他2个网站都可以访问。

**Comment by assimon** [comment]
网络问题本身跟程序没关系，你都说了移动网络效果差。独角所有静态资源都走的本地。如果是后台慢多访问几次有缓存就行了

**Comment by wangwangyh** [comment]
> 网络问题本身跟程序没关系，你都说了移动网络效果差。独角所有静态资源都走的本地。如果是后台慢多访问几次有缓存就行了

谢谢大佬回复，但是我相同的服务器，同一个域名，其他的站，移动网络都可以访问，这个站只有电信联通可以访问，移动死活访问不了。我是说前端，后台倒不所谓啦。～

**Comment by wangwangyh** [comment]
是因为静态设置的缘故吗～静态能改么？

**Comment by assimon** [comment]
跟程序应该没关系，你看我的演示站也是香港的服务器，你拿移动试试
